# Ejercicios de Numpy

                                                                            Ana Teresa Calderón Juárez
                                                                            187550

In [1]:
%pylab inline
import numpy as np

Populating the interactive namespace from numpy and matplotlib


<div class="alert alert-danger">
Esta tarea se debe de entregar el viernes 25 de septiembre, 2020 antes de las 23:59 horas.
</div>

## Pregunta 1

Crea los siguientes arreglos con los tipos correctos. 

- Un arreglo de $5 \times 5$ cuya diagonal sean $[2.0, 3.0, 4.0, 5.0]$
- Un arreglo de $4 \times 4$ cuyo último renglón sea $[1,2,3,4]$ y el resto sean $0$.

In [23]:
#Arreglo de 4x4 cuyo último renglón sea [1,2,3,4] y el resto 0
import numpy as np
a=np.array(np.zeros((4,4)),dtype=int)
a[3:]=[1,2,3,4]
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 2, 3, 4]])

In [63]:
#Arrelgo 5x5 cuya diagonal sea [2.0,3.0,4.0,5.0]
b=np.diag([2.0,3,4,5,6])
b


array([[2., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0.],
       [0., 0., 4., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 6.]])

## Pregunta 2

En este ejercicio realizaremos una [**criba de Eratóstenes**](http://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

<div class="alert alert-warning">
**Nota**: Ejercicio basado en el presentado en `C4P`.
</div>

(a) Crea un arreglo de booleanos de **shape** `(100,)`, con todos sus elementos `True`.  El índice representa el número.

In [68]:
#Arreglo de puros TRUES tamaño 100
bool_arr = np.ones((100,), dtype=bool)

(b) "Tacha" los elementos `0` y `1`.

In [69]:
#Por tachar me referiré a poner falso (0)
bool_arr[0:2]=0
bool_arr

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

(c) Para cada entero subsiguiente, tacha sus múltiplos. Una manera de hacerlo es el código que se muestra. Explica que hace el código, sobretodo explica que hace el *slicing*.

In [73]:
N_max = int(np.sqrt(len(bool_arr)))
#Se estan buscando los primos menores a 100
#el nmax es la raiz del tamaño del arreglo 
#Para que p sea primo, basta verificar que los primos menores o iguales a su raíz no lo dividen
        #ES decir, si p es compuesto y ningun primo menor a su raiz lo divide, por def p=m1*m2 con mi,m2>1 además m1>sqrt(p) 
        # y m2>sqr(t) entonces m1*m2>sqrt(p)^2=p !!!. Entonces p es primo


for j in range(2, N_max):
    bool_arr[2*j::j] = False
#Se comienza desde el 2j y va a ir amuntando de j en j,llena todos  los múltimos, justo por eso el segundo : esta vacio (sale cuando el multiplo se sale del arreglo)
#Justo el j se queda en verdadero ya que nadie atrás de él lo hizo falso.

In [74]:
bool_arr

array([False, False,  True,  True, False,  True, False,  True, False,
       False, False,  True, False,  True, False, False, False,  True,
       False,  True, False, False, False,  True, False, False, False,
       False, False,  True, False,  True, False, False, False, False,
       False,  True, False, False, False,  True, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False,  True, False,  True, False,
       False, False, False, False,  True, False, False, False,  True,
       False,  True, False, False, False, False, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False, False, False,  True, False,
       False])

In [75]:
np.nonzero(bool_arr)
#Te devuelve los indices de los que no son cero(quiénes son true, 1) en arreglo osea los primos

(array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
        61, 67, 71, 73, 79, 83, 89, 97]),)

(d) Mira la documentacion de `np.nonzero` para imprimir todos los números primos.

(e) Encapsula lo que acabamos de hacer en una función llamada `criba_eratostenes`, que reciba como argumento `maximo` el cual representa el tamaño del `array`. Muestra el resultado para `maximo = {10, 100, 200}`, usando un `for`.

In [76]:
#ESta funcion devuelve un arreglo con los numeros primos menores o iguales al argumento
def criba_eratostenes(maximo):
    #Arreglo de puros TRUES tamaño maximo
    bool_arr = np.ones((maximo,), dtype=bool)
    
    #Por tachar me referiré a poner falso (0) 0,1
    bool_arr[0:2]=0
    bool_arr

    N_max = int(np.sqrt(len(bool_arr)))
    #Se estan buscando los primos menores a 100
    #Para que p sea primo, basta verificar que los primos menores o iguales a su raíz no lo dividen



    for j in range(2, N_max):
        bool_arr[2*j::j] = False
    #Se comienza desde el 2j y va a ir amuntando de j en j,llena todos  los múltimos, justo por eso el segundo : esta vacio (sale cuando el multiplo se sale del arreglo)
    #Si es true, es primo ya que no es multiplo de nadie menor igual a su raiz 
    
    x=np.nonzero(bool_arr)
    #Te devuelve los indices de los que no son cero(quiénes son true, 1) en un arreglo osea los primos
  
    return x

In [78]:
for i in [10,100,200]:
    print (criba_eratostenes(i))

(array([2, 3, 5, 7, 9]),)
(array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97]),)
(array([  2,   3,   5,   7,  11,  13,  17,  19,  23,  29,  31,  37,  41,
        43,  47,  53,  59,  61,  67,  71,  73,  79,  83,  89,  97, 101,
       103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167,
       173, 179, 181, 191, 193, 197, 199]),)


## Pregunta 3

Crea un [cubo rubik](http://en.wikipedia.org/wiki/Rubik%27s_Cube), partiendo de un arreglo de ceros y usando *slicing* dibuja cada una de las caras como si estuviera resuelto (cada color un entero a partir del $1$). Muestra con *indexing* que está resuelto (es decir, imprime las seis caras). ¿Cuántos elementos del arreglo quedaron en $0$?

In [82]:
cubo=np.zeros((6,3,3))
cubo

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## Pregunta 4

El **Sudoku** es un pasatiempo que consiste en un arreglo  $9 \times 9$ de celdas, con dígitos del 1 al 9, de tal manera que no se repiten valores en cada columna, cada renglón y en cada subarreglo de $3\times 3$.

(a) Crea una función llamada `correcto` que reciba un `array` $1d$ de tamaño 9 e indique si está completo o no (i.e. incluye los números del 1 al 9.

(b) Crea una función llamada `descomponer3x3` que reciba un `array` de enteros de $9\times 9$ y lo separe en sus 9 subarreglos $3\times3$.

(c) Crea la función `esSolucion` que recibe un `array` de $9\times 9$ y devuelve si es o no solución del sudoku.

## Pregunta 5

Utiliza el archivo `sunspots.txt` (localizado en la carpeta `data`), el cual contiene el número de manchas solares por cada mes desde enero de 1749. La primera columna es el mes, el segundo el número de manchas.

(a) Escribe el código que lea el archivo y haga una gráfica de las manchas en función del tiempo. Formatea el eje $x$ para que se muestren cada 25 años empezando en $1750$. 

<div class="alert alert-warning">
**NOTA:** La gráfica debe de estar en calidad de publicación.
</div>

(b) Calcula el [promedio móvil](http://en.wikipedia.org/wiki/Moving_average). Dibújalo sobre el dibujo original.

## Pregunta 6

Utiliza el archivo `starts.txt` (localizado en la carpeta `data`), el cual contiene la temperatura y magnitud de varias estrellas en la Vía Lactea.  Usa esta información para dibujar un **scatter plot** del logaritmo del brillo vs. la temperatura (en **K**). Este diagrama se conoce como diagrama de [Hertzsprung-Russell](http://en.wikipedia.org/wiki/Hertzsprung%E2%80%93Russell_diagram). 

(a) Lee el archivo y dibuja los datos tal como vienen en el archivo. Agrega etiquetas y formatea la gráfica de tal manera que tenga calidad de publicación.

(b) Ahora usa el `xlim()` y  `ylim()` para que quede de manera correcta el diagrama. Hay regiones donde las estrellas parece que se aglomeran, ve el archivo de [wikipedia]( http://en.wikipedia.org/wiki/Hertzsprung%E2%80%93Russell_diagram) y agrega anotaciones para explicarlas.
