# Introducción

**NumPy** es la *librería* de python para computación científica. **NumPy** agrega al lenguaje lo siguiente: Arreglos multidimensionales, operaciones elemento por elemento (técnica conocida como *broadcasting*), algebra lineal, manipulación de imágenes, la habilidad de utilizar código `C/C++` y `FORTRAN`, entre muchas otras.

La mayor parte de los componentes del sistema de computo científico de Python, están construidas encima de **NumPy**, un ejemplo que veremos en el curso es `SciPy`.

Para poder utilizar **NumPy**, es necesario importarlo a la sesión del `notebook`.

### Bibliografía de soporte

- *NumPy Beginner's Guide* _Ivan Idris_,  PACKT Publishing, 2012
- *NumPy Cookbook* _Ivan Idris_, PACKT Publishing, 2012
- *Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython*, _Wes McKinney_, O'REILLY, 2012

In [1]:
import numpy as np

## Arrays

El principal componente de **NumPy** es el `array`, el cual es una versión más poderosa, pero menos flexible que las listas de python.

In [2]:
lst =  [1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [7]:
arr = np.array([1,2,3,4,6])
print (arr)

[1 2 3 4 6]


In [5]:
lst[2:3]

[3]

In [6]:
arr[2:3]

array([3])

<div class="alert alert-info">
**Ejercicio:** Repite los ejercicios de listas del *Lecture 2* con `array`.
</div>

In [8]:
lst[-1] = "Las listas pueden tener varios tipos de datos"
lst

[1, 2, 3, 4, 'Las listas pueden tener varios tipos de datos']

In [9]:
arr[-1] = "Los arreglos no..."

ValueError: invalid literal for int() with base 10: 'Los arreglos no...'

Una vez inicializado el `array` sólo puede contener un tipo de dato.

In [10]:
arr.dtype

dtype('int64')

In [14]:
arr[-1] = 1.8
arr

array([1, 2, 3, 4, 1])

In [12]:
arr.dtype

dtype('int64')

Sacrificamos la versatilidad de las listas por velocidad. Creeemos un `array` de 1 millón de elementos y multiplicaremos cada uno de ellos por una constante (*broadcasting*).

In [15]:
arr = np.arange(1e7)  

In [16]:
lst = arr.tolist()

Las listas no soportan *broadcasting* por lo que crearemos una función que lo simule

In [17]:
def lst_multiplicacion( alist , scalar ): 
    for i , val in enumerate ( alist ): 
        alist [ i ] = val
    return alist

In [18]:
%timeit arr * 1.1

18.2 ms ± 544 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
%timeit lst_multiplicacion(lst, 1.1)

1.27 s ± 19.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Creación de arrays

In [21]:
arr = np.array([1,2,3,4,5])

In [22]:
arr

array([1, 2, 3, 4, 5])

In [23]:
arr = np.arange(10,21)

In [24]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [25]:
arr = np.zeros(5)

In [26]:
arr

array([0., 0., 0., 0., 0.])

In [27]:
arr = np.linspace(0,1,100)

In [28]:
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [37]:
arr = np.logspace(0,1,100, base=2)

In [38]:
arr

array([1.        , 1.00702605, 1.01410147, 1.02122661, 1.0284018 ,
       1.03562741, 1.04290378, 1.05023128, 1.05761026, 1.06504109,
       1.07252413, 1.08005974, 1.0876483 , 1.09529017, 1.10298574,
       1.11073538, 1.11853947, 1.12639839, 1.13431252, 1.14228226,
       1.150308  , 1.15839013, 1.16652904, 1.17472514, 1.18297882,
       1.19129049, 1.19966056, 1.20808944, 1.21657755, 1.22512529,
       1.23373308, 1.24240136, 1.25113054, 1.25992105, 1.26877332,
       1.27768779, 1.2866649 , 1.29570508, 1.30480877, 1.31397643,
       1.3232085 , 1.33250543, 1.34186769, 1.35129572, 1.36079   ,
       1.37035098, 1.37997915, 1.38967495, 1.39943889, 1.40927142,
       1.41917304, 1.42914422, 1.43918547, 1.44929726, 1.45948011,
       1.46973449, 1.48006093, 1.49045992, 1.50093197, 1.5114776 ,
       1.52209732, 1.53279166, 1.54356114, 1.55440628, 1.56532762,
       1.5763257 , 1.58740105, 1.59855422, 1.60978575, 1.62109619,
       1.6324861 , 1.64395604, 1.65550656, 1.66713824, 1.67885

In [35]:
arr2d = np.zeros((4,5))

In [36]:
arr2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
cubo = np.zeros((5,5,5)).astype(int)+1

In [40]:
cubo

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [41]:
cubo = np.ones((5,5,5)).astype(np.float16)

In [42]:
cubo

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float16)

In [43]:
cubo.dtype

dtype('float16')

In [44]:
np.empty((2,3,4))

array([[[4.65083874e-310, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000]]])

<div class="alert alert-danger">
**PELIGRO**

¡`np.empty` no devuelve un arreglo de ceros!
</div>

In [45]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
np.random.seed(5)
np.random.rand(5)

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119])

## Reshaping

In [48]:
arr = np.arange(1000)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [53]:
arr3d = arr.reshape((10,10,10))
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [52]:
arr3d.ndim

3

In [54]:
arr3d.shape

(10, 10, 10)

In [ ]:
arr3d

In [55]:
arr = np.arange(200)

In [56]:
arr2d = arr.reshape((10,20))

In [57]:
arr2d

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
         33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 1

## Aplanar

In [59]:
arr = np.zeros((4,4,4,4))
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

      

In [60]:
arr.shape

(4, 4, 4, 4)

In [63]:
arr_plano = arr.ravel()
arr_plano

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [62]:
arr_plano.shape

(256,)

## *Broadcasting*

In [64]:
data = np.array([1,2,3,4,5])

In [65]:
data

array([1, 2, 3, 4, 5])

In [66]:
data + 1

array([2, 3, 4, 5, 6])

In [67]:
data * 2

array([ 2,  4,  6,  8, 10])

In [68]:
data ** 2

array([ 1,  4,  9, 16, 25])

## Transponer

In [69]:
arr = np.arange(15).reshape((3,5))

In [70]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [71]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

¿Qué pasa en varias dimensiones?

In [72]:
arr  = np.arange(16).reshape((2,2,4))

In [73]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [74]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

`transpose` recibe una `tupla` de los índices de los ejes y los permuta. `(O_o)`

<div class="alert alert-info">
**Ejercicio** Diseña un ejemplo multidimensional, donde sea obvia la permutación
</div>

## Slicing e Indexado

En el ejercicio vimos que el indexado en `arrays` de 1D es igual que el indexado y *slicing* de las listas de python. ¿Pero que sucede en $n-$dimensiones?

### Cuidado al hacer *slicing*

In [75]:
arr = np.arange(10)

In [76]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

El _slincing_ genera (devuelve) una **vista**, si modificas el =array= original, la **vista** se ve modificada también.

In [77]:
arr_slice =  arr[5:8]

In [78]:
arr_slice

array([5, 6, 7])

In [79]:
arr_slice[1]= 12345678

In [80]:
arr_slice

array([       5, 12345678,        7])

In [81]:
arr

array([       0,        1,        2,        3,        4,        5,
       12345678,        7,        8,        9])

In [82]:
arr_slice[:] = 345

In [83]:
arr_slice

array([345, 345, 345])

In [84]:
arr

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [85]:
arr2 = np.copy(arr)

In [86]:
arr2

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [87]:
arr2[5:8] = [5,6,7]

In [88]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
arr

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [90]:
np.may_share_memory(arr, arr_slice)

True

In [91]:
np.may_share_memory(arr, arr2)

False

### Multidimensional

In [93]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [94]:
arr.shape = (3,3)

In [95]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [98]:
arr.ndim

2

In [99]:
arr[2]

array([6, 7, 8])

In [100]:
arr[-1]

array([6, 7, 8])

In [101]:
arr[1][1]

4

In [102]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [103]:
arr[:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [104]:
arr[:1,:2]

array([[0, 1]])

In [105]:
arr[1:,:2]

array([[3, 4],
       [6, 7]])

In [106]:
arr[1,]

array([3, 4, 5])

In [107]:
arr[1,:2]

array([3, 4])

In [108]:
arr[1,2:]

array([5])

In [109]:
arr[:,1:]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [110]:
arr[:,:1]

array([[0],
       [3],
       [6]])

<div class="alert alert-info">
**Ejercicio**:

Explique como funciona el *slicing* $n$-dimensional.
</div>

In [111]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [112]:
index = arr > 2

In [113]:
index

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [114]:
arr[index]

array([3, 4, 5, 6, 7, 8])

In [115]:
arr2 = arr[index]

In [116]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [117]:
arr2

array([3, 4, 5, 6, 7, 8])

<div class="alert alert-info">
**Ejercicio:**
(a) Cree un arreglo de 2D $5\times5$ lleno de unos. (b) Utilice *slicing* para seleccionar 1 cuadrado alrededor del centro  y llénelo con $2$s.  (c) Utilice *slicing* para seleccionar  el centro y asígnele $4$. (d) Copie el arreglo. (e) Utilice *slicing* lógico para seleccionar el cuadro interno y asígnele cero. (f) En el cuadro copiado, al centro y al cuadro exterior asígnele $0$.
</div>

## Fancy Indexing

In [119]:
arr = np.ones((5,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [120]:
for i in range(5):
    arr[i] = i

In [121]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [122]:
arr[[4,3,1,2]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.]])

In [136]:
arr[[-3,-2,-1]]

array([[2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

¿Puedes explicar que hace el _fancy indexing_?

## Funciones Universales

Las *funciones universales*  realizan operaciones elemento por elemento en los arreglos. 

In [158]:
arr = np.arange(10)

In [138]:
arr = -1*arr

In [139]:
arr

array([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [140]:
arr = np.abs(arr)

In [141]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [143]:
np.sign(arr)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [144]:
np.isfinite(arr)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [162]:
np.logical_not(arr)

array([ True, False, False, False, False, False, False, False, False,
       False])

In [146]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
arr = np.random.randn(10)

In [164]:
arr

array([ 1.82444017,  1.45762512, -0.91025815, -0.99001894, -0.81754812,
       -1.16827947, -0.21077965, -0.22429966,  0.65122845, -0.96276198])

In [165]:
np.ceil(arr)

array([ 2.,  2., -0., -0., -0., -1., -0., -0.,  1., -0.])

In [166]:
np.floor(arr)

array([ 1.,  1., -1., -1., -1., -2., -1., -1.,  0., -1.])

In [167]:
np.rint(arr)

array([ 2.,  1., -1., -1., -1., -1., -0., -0.,  1., -1.])

In [168]:
arr2 = np.ones(10)

In [169]:
np.add(arr, arr2)

array([ 2.82444017,  2.45762512,  0.08974185,  0.00998106,  0.18245188,
       -0.16827947,  0.78922035,  0.77570034,  1.65122845,  0.03723802])

In [170]:
np.multiply(arr, arr2)

array([ 1.82444017,  1.45762512, -0.91025815, -0.99001894, -0.81754812,
       -1.16827947, -0.21077965, -0.22429966,  0.65122845, -0.96276198])

In [171]:
np.maximum(arr, arr2)

array([1.82444017, 1.45762512, 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ])

In [172]:
np.logical_and(arr, arr2)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## Agregaciones

Funciones que calculan operaciones a lo largo de un eje.

In [173]:
arr

array([ 1.82444017,  1.45762512, -0.91025815, -0.99001894, -0.81754812,
       -1.16827947, -0.21077965, -0.22429966,  0.65122845, -0.96276198])

In [174]:
arr.sum()

-1.3506522456302952

In [175]:
arr.mean()

-0.13506522456302952

In [176]:
arr = np.random.randn(5,4)

In [177]:
arr

array([[ 2.23874294,  0.24778538,  0.32639613,  0.26650019],
       [ 0.37746398, -0.02392064,  1.22888408, -0.39583126],
       [ 1.52502591,  0.26157022, -0.4875009 , -0.01560054],
       [ 1.13366694,  0.47173221,  1.96863378,  0.96110296],
       [-0.25369298, -0.74089058,  0.05206415, -0.52166071]])

In [178]:
arr.sum()

8.620471258542707

In [179]:
arr.mean()

0.4310235629271354

In [180]:
arr.sum(0)

array([5.0212068 , 0.21627659, 3.08847723, 0.29451063])

In [181]:
arr = np.arange(10)

In [182]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [185]:
arr.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [186]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [187]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [188]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [189]:
(arr > 5).sum()

4

## Operaciones de conjuntos

In [190]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [191]:
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [194]:
np.unique(arr2)

array([1.])

In [195]:
np.intersect1d(arr, arr2)

array([1.])

<div class="alert alert-info">
**Ejercicio** Usando la definición de [**cuadrados mágicos**](http://en.wikipedia.org/wiki/Magic_square) crea una función que reciba un arreglo e indique si es o no un cuadrado mágico.
</div>

## Casting

In [196]:
a = np.array([1,2,3])
a

array([1, 2, 3])

El tipo de mayor jerarquía define el _cast_

In [197]:
a + 1.5

array([2.5, 3.5, 4.5])

La asignación **no** cambia el tipo del arreglo.

In [198]:
a.dtype

dtype('int64')

In [199]:
(a + 1.5).dtype

dtype('float64')

## Tipos 

In [201]:
np.info(np.int64)   # Prueba con 8, 16, 32 y 64 bits

 int64()

Signed integer type, compatible with Python `int` anc C ``long``.
Character code: ``'l'``.
Canonical name: ``np.int_``.
Alias *on this platform*: ``np.int64``: 64-bit signed integer (-9223372036854775808 to 9223372036854775807).
Alias *on this platform*: ``np.intp``: Signed integer large enough to fit pointer, compatible with C ``intptr_t``.


Methods:

  all  --  Not implemented (virtual attribute)
  any  --  Not implemented (virtual attribute)
  argmax  --  Not implemented (virtual attribute)
  argmin  --  Not implemented (virtual attribute)
  argsort  --  Not implemented (virtual attribute)
  astype  --  Not implemented (virtual attribute)
  byteswap  --  Not implemented (virtual attribute)
  choose  --  Not implemented (virtual attribute)
  clip  --  Not implemented (virtual attribute)
  compress  --  Not implemented (virtual attribute)
  conj  --  None
  conjugate  --  Not implemented (virtual attribute)
  copy  --  Not implemented (virtual attribute)
  cumprod  --  Not 

<div class="alert alert-info">
**Ejercicio** ¿Qué pasa con `int`?
</div>

In [202]:
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [206]:
np.finfo(np.float64).eps

2.220446049250313e-16

In [204]:
np.float32(1e-8) + np.float32(1) == 1

True

In [205]:
np.float64(1e-8) + np.float64(1) == 1

False

## Estructura de datos

In [207]:
muestra = np.zeros((6,), dtype=[('codigo', 'S4'),('posicion', float), ('valor', float)])

In [208]:
muestra

array([(b'', 0., 0.), (b'', 0., 0.), (b'', 0., 0.), (b'', 0., 0.),
       (b'', 0., 0.), (b'', 0., 0.)],
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

In [209]:
muestra.ndim

1

In [210]:
muestra.shape

(6,)

In [211]:
muestra.dtype.names

('codigo', 'posicion', 'valor')

In [212]:
muestra[:] = [('ALFA',   1, 0.37), ('BETA', 1, 0.11), ('TAU', 1,   0.13),('ALFA', 1.5, 0.37), ('ALFA', 3, 0.11), ('TAU', 1.2, 0.13)]

In [213]:
muestra

array([(b'ALFA', 1. , 0.37), (b'BETA', 1. , 0.11), (b'TAU', 1. , 0.13),
       (b'ALFA', 1.5, 0.37), (b'ALFA', 3. , 0.11), (b'TAU', 1.2, 0.13)],
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

In [214]:
muestra.shape

(6,)

In [215]:
muestra['codigo']

array([b'ALFA', b'BETA', b'TAU', b'ALFA', b'ALFA', b'TAU'], dtype='|S4')

In [216]:
muestra[0]['valor']

0.37

In [217]:
muestra[['codigo', 'valor']]

array([(b'ALFA', 0.37), (b'BETA', 0.11), (b'TAU', 0.13), (b'ALFA', 0.37),
       (b'ALFA', 0.11), (b'TAU', 0.13)],
      dtype={'names':['codigo','valor'], 'formats':['S4','<f8'], 'offsets':[0,12], 'itemsize':20})

In [218]:
muestra[muestra['codigo'] == 'ALFA']

array([], shape=(0, 6),
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

## Broadcasting (Segunda vuelta)

<div class="alert alert-warning">
**NOTA** Las imágenes y ejemplos están basados en la presentación  **The NumPy Array: A Structure for
Efficient Numerical Computation** de _Stéfan van der Walt_ de 2010.
</div>

### 1D

<img src="images/broadcasting_1d.png"/>

In [219]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [220]:
x + 3

array([3, 4, 5, 6])

### 2D

<img src="images/broadcasting_2d.png"/>

In [221]:
a = np.arange(12).reshape((3,4))
print( a.shape)
a

(3, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [222]:
b = np.array([1,2,3])
print( b.shape)
b

(3,)


array([1, 2, 3])

In [223]:
a+b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

<div class="alert alert-danger">
**Observa muy bien lo que acaba de pasar, el error es a propósito...**
</div>

In [224]:
b = b[:, np.newaxis]
print (b.shape)
b

(3, 1)


array([[1],
       [2],
       [3]])

In [225]:
a + b

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])