# **Ejercicios de NumPy**

In [1]:
%pylab inline
import numpy as np

Populating the interactive namespace from numpy and matplotlib


## Pregunta 1
Crea los siguientes arreglos con los tipos correctos. 
- Un arreglo de $5 \times 5$ cuya diagonal sean $[2.0, 3.0, 4.0, 5.0]$
- Un arreglo de $4 \times 4$ cuyo último renglón sea $[1,2,3,4]$ y el resto sean $0$.

In [2]:
lista=list(range(1,6))
ListaSuprema=[]
for i in range(5):
    ListaSuprema.append(lista)
arr1=np.array(ListaSuprema).astype(np.float16)
print(arr1)

[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


In [3]:
arr2=np.zeros((4,4)).astype(int)
arr2[3]=np.arange(1,5).astype(int)
print(arr2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


## Pregunta 2
En este ejercicio realizaremos una [**criba de Eratóstenes**](http://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)


<div class="alert alert-warning">
**Nota**: Ejercicio basado en el presentado en `C4P`.
</div>

(a) Crea un arreglo de booleanos de **shape** `(100,)`, con todos sus elementos `True`.  El índice representa el número.

In [4]:
bool_arr = np.ones((100,), dtype=bool)
print(bool_arr)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]


(b) "Tacha" los elementos `0` y `1`.

In [5]:
bool_arr[0]=False
bool_arr[1]=False

(c) Para cada entero subsiguiente, tacha sus múltiplos. Una manera de hacerlo es el código que se muestra. Explica que hace el código, sobretodo explica que hace el *slicing*.

In [9]:
N_max = int(np.sqrt(len(bool_arr)))
for j in range(2, N_max):
    bool_arr[2*j::j] = False

#Este método funciona así:
#1. Se obtiene la raíz cuadrada de la longitud del arreglo, ya que alguna potencia mayor a dos de algún número mayor a la raíz obtenida queda fuera del intervalo
#2. Se convierten en falso todos los múltiplos de j, para toda j menor a la raíz obtenida en el inciso anterior
    #2.1 El slicing funciona así:
        #2.1.1 Empieza en el doble de j y termina en el final del array y se dan saltos de tamaño j para eliminar los múltiplos de j

In [13]:
#Otra manera de hacerlo es yendo de 2 al final del arreglo y empezando en el cuadrado de j y dando saltos de tamaño j y así se repiten menos procesos
bool_ar = np.ones((100,), dtype=bool)
N_max = int(np.sqrt(len(bool_ar)))
for j in range(2, N_max):
    bool_ar[j*j::j] = False
#Este método funciona así:
#1. Se obtiene la raíz cuadrada de la longitud del arreglo, ya que alguna potencia mayor a dos de algún número mayor a la raíz obtenida queda fuera del intervalo
#2. Se convierten en falso el cuadrado j y los múltiplos de j, para toda j menor a la raíz obtenida en el inciso anterior
    #2.1 El slicing funciona así:
        #2.1.1 Empieza en el cuadrado de j y termina en el final del array y se dan saltos de tamaño j para eliminar los múltiplos de j


(d) Mira la documentacion de np.nonzero para imprimir todos los números primos.

In [17]:
np.nonzero(bool_arr)

(array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
        61, 67, 71, 73, 79, 83, 89, 97]),)

(e) Encapsula lo que acabamos de hacer en una función llamada criba_eratostenes, que reciba como argumento maximo el cual representa el tamaño del array. Muestra el resultado para maximo = {10, 100, 200}, usando un for.

In [20]:
def criba_eratostenes(n):
    bool_arr = np.ones((n,), dtype=bool)
    bool_arr[0]=False
    bool_arr[1]=False
    N_max = int(np.sqrt(len(bool_arr)))
    for j in range(2, N_max):
        bool_arr[2*j::j] = False
    print(np.nonzero(bool_arr))

In [36]:
conjunto={10,100,200}
print('Los número primos del máximo de (10,100,200) son: ')
criba_eratostenes(max(conjunto))


Los número primos del máximo de (10,100,200) son: 
(array([  2,   3,   5,   7,  11,  13,  17,  19,  23,  29,  31,  37,  41,
        43,  47,  53,  59,  61,  67,  71,  73,  79,  83,  89,  97, 101,
       103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167,
       173, 179, 181, 191, 193, 197, 199]),)


## Pregunta 3
Crea un [cubo rubik](http://en.wikipedia.org/wiki/Rubik%27s_Cube), partiendo de un arreglo de ceros y usando *slicing* dibuja cada una de las caras como si estuviera resuelto (cada color un entero a partir del $1$). Muestra con *indexing* que está resuelto (es decir, imprime las seis caras). ¿Cuántos elementos del arreglo quedaron en $0$?

In [43]:
rubik=np.zeros((6,3,3)).astype(int)
for i in range (6):
    rubik[i]=i+1
print(rubik)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[4 4 4]
  [4 4 4]
  [4 4 4]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[6 6 6]
  [6 6 6]
  [6 6 6]]]
