## Introducción

- **I/O** significa _input/output_. 
- Escribir y leer datos desde archivos u otras fuentes, es fundamental en la programación, y más aún en programación científica.


## Leer archivos

In [1]:
%%file inout.dat
Hola, desde el archivo
Este es un archivo de texto
Escrito en ASCII

Writing inout.dat


Lee el archivo de una sola pasada

In [2]:
archivo = open('inout.dat')
print (archivo.read())
archivo.close()

Hola, desde el archivo
Este es un archivo de texto
Escrito en ASCII



Línea por línea

In [3]:
archivo = open('inout.dat')
print(archivo.readlines())
archivo.close()

['Hola, desde el archivo\n', 'Este es un archivo de texto\n', 'Escrito en ASCII\n']


Otra manera

In [4]:
for line in open('inout.dat'):
    print (line.split())

['Hola,', 'desde', 'el', 'archivo']
['Este', 'es', 'un', 'archivo', 'de', 'texto']
['Escrito', 'en', 'ASCII']


## Escribir archivos

`write()` es lo contrario a `read()` (¡Vaya sorpresa!)

In [5]:
contents = open('inout.dat').read()
out = open('my_output.dat', 'w')
out.write(contents.replace(' ', '_'))
out.close()

In [6]:
!cat my_output.dat

Hola,_desde_el_archivo
Este_es_un_archivo_de_texto
Escrito_en_ASCII


<div class="alert alert-info">
**Ejercicio** Cambia la segunda línea del archivo a _¿Cómo has estado?_ ¿Qué sucede?
</div>

<div class="alert alert-info">
**Ejercicio** Escribe un archivo `CSV`. Calcula $y(x) = x^2 \cos x$ para los valores del $x \in {1..100}$. En la primera columna guarda $x$ y en la segunda $y(x)$.
</div>

In [7]:
import math
out = open('archivo.csv', 'w')
for x in range(1,101):
    #out.write('{},{}\n'.format(x, x**2*math.cos(x)))\
    out.write( str(x) + ',' + str(x**2*math.cos(x)) + '\n')
out.close()
!cat archivo.csv

1,0.5403023058681398
2,-1.6645873461885696
3,-8.909932469404009
4,-10.458297933817791
5,7.091554636580656
6,34.566130319413176
7,36.94121046282193
8,-9.312002163751266
9,-73.80155121265884
10,-83.90715290764524
11,0.5355094565541451
12,121.51497005747886
13,153.35850606508316
14,26.800494768735387
15,-170.9297803932348
16,-245.16082696278647
17,-79.52220469691152
18,213.94261347108198
19,356.9223671653876
20,163.23282472535678
21,-241.54860375890235
22,-483.98103997500436
23,-281.8686677563673
24,244.32710822611025
25,619.501757414671
26,437.3174618941609
27,-212.96919156696657
28,-754.6829991898362
29,-629.1163824684493
30,138.82630489882564
31,879.0674058501546
32,854.2447211586665
33,-14.458377725911772
34,-980.9472376510037
35,-1107.0229512370956
36,-165.84094175711647
37,1047.8518371131752
38,1379.1263420042937
39,405.56390011946456
40,-1067.100898643619
41,-1659.7173255175524
42,-705.5740956394517
43,1026.4044945116368
44,1935.6966455419301
45,1063.7770273559026
46,-914.488531376

## Numpy I/O

In [8]:
%pylab inline
import numpy as np
import matplotlib.pyplot as plt

Populating the interactive namespace from numpy and matplotlib


- `NumPy` permite escribir y leer los arreglos a archivo de varias maneras, como **texto** o en **binario**.
- Si escribes a un archivo usando el modo de **texto**, el número $\pi$, se escribirá como $3.141592653589793$. Algo que un humano puede leer (bajo ciertas condiciones, obvio), es decir, una cadena de texto. El modo de texto, ocupa más espacio, la precisión se puede perder (no todos los dígitos se escribirán al disco), pero puede ser editada a mano. Si guardas un arreglo, sólo se pueden guardar arreglos bidimensionales.
- En cambio, si usas el modo **binario** para escribir a archivo, se escribirá como una cadena de 8 bytes que será idéntica a como se guarda en la memoria de la computadora. Sus únicas desventaja es que no puede ser editado a mano y que es dependiente de `NumPy` (no puede ser leído por otro programa, sin un convertidor).

## Modo Texto

In [9]:
arr = np.arange(100).reshape(10, 10)
np.savetxt('test.out', arr, fmt='%.2e', header="My dataset")
!cat test.out

# My dataset
0.00e+00 1.00e+00 2.00e+00 3.00e+00 4.00e+00 5.00e+00 6.00e+00 7.00e+00 8.00e+00 9.00e+00
1.00e+01 1.10e+01 1.20e+01 1.30e+01 1.40e+01 1.50e+01 1.60e+01 1.70e+01 1.80e+01 1.90e+01
2.00e+01 2.10e+01 2.20e+01 2.30e+01 2.40e+01 2.50e+01 2.60e+01 2.70e+01 2.80e+01 2.90e+01
3.00e+01 3.10e+01 3.20e+01 3.30e+01 3.40e+01 3.50e+01 3.60e+01 3.70e+01 3.80e+01 3.90e+01
4.00e+01 4.10e+01 4.20e+01 4.30e+01 4.40e+01 4.50e+01 4.60e+01 4.70e+01 4.80e+01 4.90e+01
5.00e+01 5.10e+01 5.20e+01 5.30e+01 5.40e+01 5.50e+01 5.60e+01 5.70e+01 5.80e+01 5.90e+01
6.00e+01 6.10e+01 6.20e+01 6.30e+01 6.40e+01 6.50e+01 6.60e+01 6.70e+01 6.80e+01 6.90e+01
7.00e+01 7.10e+01 7.20e+01 7.30e+01 7.40e+01 7.50e+01 7.60e+01 7.70e+01 7.80e+01 7.90e+01
8.00e+01 8.10e+01 8.20e+01 8.30e+01 8.40e+01 8.50e+01 8.60e+01 8.70e+01 8.80e+01 8.90e+01
9.00e+01 9.10e+01 9.20e+01 9.30e+01 9.40e+01 9.50e+01 9.60e+01 9.70e+01 9.80e+01 9.90e+01


In [10]:
DataIn = np.loadtxt('test.out')
print (DataIn.shape)
print (DataIn)

(10, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]
 [50. 51. 52. 53. 54. 55. 56. 57. 58. 59.]
 [60. 61. 62. 63. 64. 65. 66. 67. 68. 69.]
 [70. 71. 72. 73. 74. 75. 76. 77. 78. 79.]
 [80. 81. 82. 83. 84. 85. 86. 87. 88. 89.]
 [90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]]


In [ ]:
print (DataIn[1,:])

#### Leyendo archivos CSV

In [ ]:
%%file input.csv
# Mis datos de ejemplo
    0.0,  1.1,  0.1
    2.0,  1.9,  0.2
    4.0,  3.2,  0.1
    6.0,  4.0,  0.3
    8.0,  5.9,  0.3

In [ ]:
!cat input.csv

In [ ]:
x, y = np.loadtxt('input.csv', unpack=True, delimiter=',', usecols=[0,1])
print(x,y)

## Modo Binario

Para guardar datos binarios, `NumPy` provee los métodos `np.save` y `np.savez`. El primero sólo guarda un arreglo y el archivo tendrá la extensión `.npy`, mientras que el segundo se puede utilizar para guardar varios arreglos a la vez con una extensión `.npz`.

In [ ]:
arr2 = DataIn 
np.save('test.npy', arr2)
# Lo leemos de nuevo
arr2n = np.load('test.npy')
# Veamos si hay una diferencia...
print( 'Any differences?', np.any(arr2-arr2n))

In [ ]:
np.savez('test.npz', arr, arr2)
arrays = np.load('test.npz')
arrays.files

In [ ]:
np.savez('test.npz', array1=arr, array2=arr2)
arrays = np.load('test.npz')
arrays.files

In [ ]:
print( 'First row of first array:', arrays['array1'][0])
# Este es una manera equivalente de obtener el primer elemento
print ('First row of first array:', arrays.f.array1[0])

<div class="alert alert-info">
**Ejercicio**: <br/>
- Crea un arreglo bidimensional con 100 elementos flotantes al azar y guárdalos en formato de texto. <br/>

- Guárdalos también en formato binario. ¿Hay alguna diferencia entre ellos? <br/>

- Ahora crea un arreglo tridimensional con los elementos del 1 al 50 y guárdalos en formato binario ¿Qué pasa si los quieres guardar en formato de texto?
</div>