In [1]:
import numpy as np

In [2]:
#aqui cada 0 seria una pieza del cubo, pero cada pieza tiene puede tener desde i hasta 3 colores.
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [4]:
#Entonces para modelar el Cubo de Rubick, diremos que cada pieza del cubo tiene 3 dimensiones
arr=np.zeros((3,3,3,3))
arr

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

### Para diferenciar las dimensiones de cada una de las piezas establecemos que, mirando solo una cara del cubo de frente en una posicion plana:
### la dimension 0 de las piezas es la que apunta hacia nosotros, o lejos de nosotros, dependiendo de la cara
### la dimension 1 es la que mira hacia arriba o hacia abajo, dependiendo de cual cara sea
### la dimension 2 es la que mira a nuestra izquierda o derecha, dependiendo de cual cara sea

In [5]:
#Aqui todas las columnas y todos los renglones del nivel 1 de profundidad.
#la primera dimension de esas piezas es igual a 1 
#La cara mirando hacia nosotros es de color "1"
arr[:,:,0,0]=1

In [6]:
arr[0,:,:,1]=2
#Aqui igualamos la cara que apunta hacia arriba al color "2"

In [7]:
arr[2,:,:,1]=3
#Aqui igualamos la cara que apunta hacia abajo al color "3"

In [8]:
arr[:,:,2,0]=4
#Aqui igualamos la cara opuesta a nosotros al color "4"

In [9]:
arr[:,2,:,2]=5
#Aqui igualamos la cara a nuestra derecha al color "5"

In [10]:
arr[:,0,:,2]=6
#Igualamos la cara a nuestra izquierda al color "6"

## Imprimimos las caras

In [11]:
#por ejemplo, para imprimie la cara de frente a nosotros, queremos todos los reglones,
#todas las columnas, del nivel de profundidad 0, de la dimension de pieza 0, entonces:
arr[:,:,0,0]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# Analogamente, la cara de atras:
arr[:,:,2,0]

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [13]:
#La de arriba
arr[0,:,:,1]

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [14]:
#la de abajo
arr[2,:,:,1]

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [15]:
#de la izquierda
arr[:,0,:,2]

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [16]:
#de la derecha
arr[:,2,:,2]

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

## Ahora vemos cuantos elementos son 0

In [17]:
#donde haya ceros en el arreglo, los remplaza por un 1 y en los demas casos lo remplaza por un 0
#Sumamos los elementos de este nuevo arreglo
np.sum(np.where(arr==0,1,0))

27