# **Ejercicios de NumPy**

In [1]:
%pylab inline
import numpy as np

Populating the interactive namespace from numpy and matplotlib


**Pregunta 1**

Crea los siguientes arreglos con los tipos correctos: 
    
   - Un arreglo de $5 \times 5$ cuya diagonal sean $[2.0, 3.0, 4.0, 5.0]$
   - Un arreglo de $4 \times 4$ cuyo último renglón sea $[1,2,3,4]$ y el resto sean $0$.

In [27]:
A = np.eye(5)
A[1][1] = 2.0
A[2][2] = 3.0
A[3][3] = 4.0
A[4][4] = 5.0
A

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

In [23]:
B = np.zeros((4,4))
B[3] = [1,2,3,4]
B

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 2., 3., 4.]])

**Pregunta 2**

(a) Crea un arreglo de booleanos de **shape** `(100,)`, con todos sus elementos `True`.  El índice representa el número.

In [83]:
bool_arr = np.ones((100,), dtype=bool)
bool_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

(b) "Tacha" los elementos `0` y `1`.

In [85]:
for i in range(0,len(bool_arr)):
    if i <= 1:
        bool_arr[i] = False

In [86]:
bool_arr

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

(c) Para cada entero subsiguiente, tacha sus múltiplos. Una manera de hacerlo es el código que se muestra. Explica que hace el código, sobretodo explica que hace el *slicing*.

In [88]:
N_max = int(np.sqrt(len(bool_arr)))
for j in range(2, N_max):
    bool_arr[2*j::j] = False

In [89]:
bool_arr

array([False, False,  True,  True, False,  True, False,  True, False,
       False, False,  True, False,  True, False, False, False,  True,
       False,  True, False, False, False,  True, False, False, False,
       False, False,  True, False,  True, False, False, False, False,
       False,  True, False, False, False,  True, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False,  True, False,  True, False,
       False, False, False, False,  True, False, False, False,  True,
       False,  True, False, False, False, False, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False, False, False,  True, False,
       False])

La variable "N_max" considera la longitud del arreglo, que es 100, pues está conformado por 100 elementos de tipo booleano. A esta longitud le calcula la raíz cuadrada y dicho valor lo convierte en un número entero. Como en este caso el índice de cada elemento representa el "número del elemento", al 100 ser el número máximo, entonces 10 es la raíz cuadrada máxima que podemos obtener dados estos números.

Posteriormente hace una iteración que va del dos a N_max, es decir de 2 a 9 (pues no contempla a 10), lo que equivale a todas las raíces cuadradas enteras resultantes dentro el conjunto de números (índices de los elementos booleanos).

Para entender el slicing, es importante tener presente que está siendo aplicando a los índices de los elementos, no directamente al contenido (True/False) de cada uno de ellos.
Antes de los dos puntos (::) tenemos el punto de inicio que será el producto de cada uno de los enteros del rango en cuestión, por dos. Así empieza a considerar a partir del primer múltiplo de cada número (sin considerar al mismo número). A partir de ese primer múltiplo entonces va contando de x en x, siendo x cada una de las raíces cuadradas (los x números que se van agregando es lo que indica el lado derecho de los dos puntos "::"). De esta manera va considerando a los múltiplos de cada uno de los enteros. 

(d) Mira la documentacion de `np.nonzero` para imprimir todos los números primos.

In [90]:
np.nonzero?

In [91]:
np.nonzero(bool_arr)

(array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
        61, 67, 71, 73, 79, 83, 89, 97]),)

(e) Encapsula lo que acabamos de hacer en una función llamada `criba_eratostenes`, que reciba como argumento `maximo` el cual representa el tamaño del `array`. Muestra el resultado para `maximo = {10, 100, 200}`, usando un `for`.

In [102]:
def criba_eratostenes(maximo):
    bool_arr = np.ones((maximo,), dtype = bool)
    N_max = int(np.sqrt(len(bool_arr)))
    for i in range(0,len(bool_arr)):
        if i <= 1:
            bool_arr[i] = False
    for j in range(2, N_max):
        bool_arr[2*j::j] = False
    primos = np.nonzero(bool_arr)
    return primos

In [103]:
maximo = {10,100,200}
for i in maximo: 
    print("Los números primos de:", i, "son: ", criba_eratostenes(i),"\n")

Los números primos de: 200 son:  (array([  2,   3,   5,   7,  11,  13,  17,  19,  23,  29,  31,  37,  41,
        43,  47,  53,  59,  61,  67,  71,  73,  79,  83,  89,  97, 101,
       103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167,
       173, 179, 181, 191, 193, 197, 199]),) 

Los números primos de: 10 son:  (array([2, 3, 5, 7, 9]),) 

Los números primos de: 100 son:  (array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97]),) 



**Pregunta 3**

Crea un cubo rubik, partiendo de un arreglo de ceros y usando slicing dibuja cada una de las caras como si estuviera resuelto (cada color un entero a partir del  1 ). Muestra con indexing que está resuelto (es decir, imprime las seis caras). ¿Cuántos elementos del arreglo quedaron en  0 ?

In [167]:
def carasRubik(caras, renglones, columnas): 
    Rubik = np.zeros((caras, renglones, columnas))
    for i in range(0,6):
        Rubik[i] = Rubik[i].astype(int)+(i+1)
        print ("Cara ", i+1, ":","\n", Rubik[i], "\n")

In [168]:
Rubik = carasRubik(6,3,3)

Cara  1 : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

Cara  2 : 
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]] 

Cara  3 : 
 [[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]] 

Cara  4 : 
 [[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]] 

Cara  5 : 
 [[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]] 

Cara  6 : 
 [[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]] 



Observamos que ahora ninguno de los elementos del arreglo es 0, todos han sido modificados por los enteros entre el 1 y el 6. 

**Problema 4**

El **Sudoku** es un pasatiempo que consiste en un arreglo  $9 \times 9$ de celdas, con dígitos del 1 al 9, de tal manera que no se repiten valores en cada columna, cada renglón y en cada subarreglo de $3\times 3$.

(a) Crea una función llamada `correcto` que reciba un `array` $1d$ de tamaño 9 e indique si está completo o no (i.e. incluye los números del 1 al 9.

In [184]:
def correcto(arreglo):
    listaCompleta = []
    if len(arreglo) == 9:
        for i in range(1,10):
            if i in arreglo and i not in listaCompleta:
                listaCompleta.append(i)        
    else: 
        print("Favor de ingresar un arreglo de tamaño 9")
    if len(listaCompleta) == 9:
        return True

In [185]:
arr = np.arange()
correcto(arr)

(b) Crea una función llamada `descomponer3x3` que reciba un `array` de enteros de $9\times 9$ y lo separe en sus 9 subarreglos $3\times3$.

(c) Crea la función `esSolucion` que recibe un `array` de $9\times 9$ y devuelve si es o no solución del sudoku.

**Pregunta 5**

Utiliza el archivo `sunspots.txt` (localizado en la carpeta `data`), el cual contiene el número de manchas solares por cada mes desde enero de 1749. La primera columna es el mes, el segundo el número de manchas.

(a) Escribe el código que lea el archivo y haga una gráfica de las manchas en función del tiempo. Formatea el eje $x$ para que se muestren cada 25 años empezando en $1750$. 

<div class="alert alert-warning">
**NOTA:** La gráfica debe de estar en calidad de publicación.
</div>

(b) Calcula el [promedio móvil](http://en.wikipedia.org/wiki/Moving_average). Dibújalo sobre el dibujo original.

**Pregunta 6**

Utiliza el archivo `starts.txt` (localizado en la carpeta `data`), el cual contiene la temperatura y magnitud de varias estrellas en la Vía Lactea.  Usa esta información para dibujar un **scatter plot** del logaritmo del brillo vs. la temperatura (en **K**). Este diagrama se conoce como diagrama de [Hertzsprung-Russell](http://en.wikipedia.org/wiki/Hertzsprung%E2%80%93Russell_diagram). 

(a) Lee el archivo y dibuja los datos tal como vienen en el archivo. Agrega etiquetas y formatea la gráfica de tal manera que tenga calidad de publicación.

(b) Ahora usa el `xlim()` y  `ylim()` para que quede de manera correcta el diagrama. Hay regiones donde las estrellas parece que se aglomeran, ve el archivo de [wikipedia]( http://en.wikipedia.org/wiki/Hertzsprung%E2%80%93Russell_diagram) y agrega anotaciones para explicarlas.
