# Ejercicios de NumPy

In [1]:
%pylab inline
import numpy as np

Populating the interactive namespace from numpy and matplotlib


## Problema 1
### Crea los siguientes arreglos con los tipos correctos:
### Un arreglo de  5×5  cuya diagonal sean  [1.0,2.0,3.0,4.0,5.0] 
### Un arreglo de  4×4  cuyo último renglón sea  [1,2,3,4]  y el resto sean  0 .

In [69]:
arrinicial = np.random.rand(25) #Van a ser 25 números
arrinicial[0] = 1.0
arrinicial[6] = 2.0 
arrinicial[12] = 3.0 #Con esto sustituimos los valores que nos piden en específico
arrinicial[18] = 4.0
arrinicial[24] = 5.0

In [70]:
arr5x5 = arrinicial.reshape(5, 5) #Los ordenamos para que sea 5 * 5

In [71]:
arr4x4 = np.zeros((4, 4)) #Llenamos todo de 0s

In [73]:
arr4x4[3]= [1, 2, 3, 4] #Sustituimos el último renglon para que sea lo que queremos

In [74]:
print(arr5x5) #Inciso 1
print(arr4x4) #Inciso 2

[[1.         0.98627037 0.10521725 0.14855512 0.18482019]
 [0.09740957 2.         0.89422811 0.70231999 0.90767057]
 [0.23922312 0.41062334 3.         0.19380221 0.86230776]
 [0.82877027 0.47284247 0.7131402  4.         0.55144369]
 [0.23732018 0.81802346 0.13654128 0.7816454  5.        ]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 2. 3. 4.]]


## Problema 2
### La criba de Eratóstenes

In [167]:
bool_arr = np.ones((100,), dtype=bool)

In [168]:
bool_arr[0 : 2] = False

In [171]:
N_max = int(np.sqrt(len(bool_arr)))
for j in range(2, N_max):
abool_arr[2*j::j] = False #La neta solo entiendo que multiplicamos por 2 para no agarrar el número y de ahí sacamos los múltiplos haciendolos falsos pero no entiendo la última j en que afecta muy bien

In [172]:
np.nonzero(bool_arr)

(array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
        61, 67, 71, 73, 79, 83, 89, 97]),)

In [163]:
def criba_eratostenes(maximo):
    bool_arr = np.ones((maximo, ), dtype=bool)
    bool_arr[0: 2] = False
    N_max = int(np.sqrt(len(bool_arr)))
    for j in range(2, N_max):
        bool_arr[2*j::j] = False
    print(np.nonzero(bool_arr))

In [164]:
print(criba_eratostenes(10))
print(criba_eratostenes(100))
print(criba_eratostenes(200))

(array([2, 3, 5, 7, 9]),)
None
(array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97]),)
None
(array([  2,   3,   5,   7,  11,  13,  17,  19,  23,  29,  31,  37,  41,
        43,  47,  53,  59,  61,  67,  71,  73,  79,  83,  89,  97, 101,
       103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167,
       173, 179, 181, 191, 193, 197, 199]),)
None


## Problema 3
### Cubo rubik

In [176]:
rubik = np.zeros((6, 3, 3)) #Partimos de puro 0

In [192]:
rojo = rubik[0]
amarillo = rubik[1]
azul = rubik[2] #Con estas funciones agarramos cada una de las caras del cubo
verde = rubik[3]
blanco = rubik[4]
naranja = rubik[5]

In [193]:
rojo[:] = 1
amarillo[:] = 2
azul[:] = 3    #Aqui a cada cara le damos un número que es su color. Cada color tiene su respectivo número
verde[:] = 4
blanco[:] = 5
naranja[:] = 6

In [194]:
rubik #Podemos ver que ningún elemento quedo en 0

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]],

       [[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]]])

## Pregunta 4
### Sudoku

In [230]:
def correcto(arreglo):
    if arreglo.ndim == 1: #Que el arreglo sea de dimensión 1
        for i in range(1, 10):
            if i in arreglo:  #Que esten los números del 1 al 9 en el arreglo
                if len(arreglo) == 9: #Que nada mas tenga 9 números
                    Correcto = True
                else:
                    Correcto = False
            else:
                Correcto = False
    else:
        Correcto = False
    return Correcto

In [249]:
def descomponer3x3(arreglo):
    if arreglo.shape==(9, 9):
        arrordenado = arreglo.resahpe(9, 3, 3) #Aqui tengo problemas porque no se como ordenarlos en los arreglos ahora en 3 x 3
    return arrordenado

In [296]:
def esSolucion(arreglo):
    if arreglo.shape==(9, 9):
        for i in range(1, 10):
            if correcto(arreglo[i]) == True: #Aquí checamos las filas
                if correcto(arreglo[:,i-1:i]) == True: #Aquí checamos las columnas
                    sudokudescompuesto = descomponer3x3(arreglo) #Descomponemos lo que tenemos
    for j in range(1, 10):
        for k in range(0, 10):
            if j in sudokudescompuesto[k]: #Checamos que cada cuadro tenga los números del 1 al 9
                print("Felicidades. El sudoku esta correcto")
            else:
                print("El sudoku esta mal")

## Problema 5
### Gráfiquitas

In [297]:
archivo = open("/week3/data/sunspots", "r") #No puedo abrir el archivo 

FileNotFoundError: [Errno 2] No such file or directory: '/week3/data/sunspots'