# Introducción

**NumPy** es la *librería* de python para computación científica. **NumPy** agrega al lenguaje lo siguiente: Arreglos multidimensionales, operaciones elemento por elemento (técnica conocida como *broadcasting*), algebra lineal, manipulación de imágenes, la habilidad de utilizar código `C/C++` y `FORTRAN`, entre muchas otras.

La mayor parte de los componentes del sistema de computo científico de Python, están construidas encima de **NumPy**, un ejemplo que veremos en el curso es `SciPy`.

Para poder utilizar **NumPy**, es necesario importarlo a la sesión del `notebook`.

### Bibliografía de soporte

- *NumPy Beginner's Guide* _Ivan Idris_,  PACKT Publishing, 2012
- *NumPy Cookbook* _Ivan Idris_, PACKT Publishing, 2012
- *Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython*, _Wes McKinney_, O'REILLY, 2012

In [1]:
import numpy as np

## Arrays

El principal componente de **NumPy** es el `array`, el cual es una versión más poderosa, pero menos flexible que las listas de python.

In [2]:
lst =  [1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
lst[2:3]

[3]

In [5]:
arr[2:3]

array([3])

<div class="alert alert-info">
**Ejercicio:** Repite los ejercicios de listas del *Lecture 2* con `array`.
</div>

In [6]:
lst[-1] = "Las listas pueden tener varios tipos de datos"
lst

[1, 2, 3, 4, 'Las listas pueden tener varios tipos de datos']

In [10]:
arr[-1] = "Los arreglos no..."

ValueError: invalid literal for int() with base 10: 'Los arreglos no...'

Una vez inicializado el `array` sólo puede contener un tipo de dato.

In [11]:
arr.dtype

dtype('int64')

In [12]:
arr[-1] = 1.23456
arr

array([1, 2, 3, 4, 1])

Sacrificamos la versatilidad de las listas por velocidad. Creeemos un `array` de 1 millón de elementos y multiplicaremos cada uno de ellos por una constante (*broadcasting*).

In [22]:
arr = np.arange(1e7)  

In [23]:
lst = arr.tolist()

Las listas no soportan *broadcasting* por lo que crearemos una función que lo simule

In [15]:
def lst_multiplicacion( alist , scalar ): 
    for i , val in enumerate ( alist ): 
        alist [ i ] = val*1.1
    return alist

In [18]:
%timeit arr * 1.1

35.5 ms ± 8.81 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [17]:
%timeit lst_multiplicacion(lst, 1.1)

1.79 s ± 135 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Creación de arrays

In [24]:
arr = np.array([1,2,3,4,5])

In [20]:
arr

array([1, 2, 3, 4, 5])

In [25]:
arr = np.arange(10,21)

In [26]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [27]:
arr = np.zeros(5)

In [28]:
arr

array([0., 0., 0., 0., 0.])

In [29]:
arr = np.linspace(0,1,100)

In [30]:
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [31]:
arr = np.logspace(0,1,100, base=10)

In [32]:
arr

array([ 1.        ,  1.02353102,  1.04761575,  1.07226722,  1.09749877,
        1.12332403,  1.149757  ,  1.17681195,  1.20450354,  1.23284674,
        1.26185688,  1.29154967,  1.32194115,  1.35304777,  1.38488637,
        1.41747416,  1.45082878,  1.48496826,  1.51991108,  1.55567614,
        1.59228279,  1.62975083,  1.66810054,  1.70735265,  1.7475284 ,
        1.78864953,  1.83073828,  1.87381742,  1.91791026,  1.96304065,
        2.009233  ,  2.05651231,  2.10490414,  2.15443469,  2.20513074,
        2.25701972,  2.3101297 ,  2.36448941,  2.42012826,  2.47707636,
        2.53536449,  2.59502421,  2.65608778,  2.71858824,  2.7825594 ,
        2.84803587,  2.91505306,  2.98364724,  3.05385551,  3.12571585,
        3.19926714,  3.27454916,  3.35160265,  3.43046929,  3.51119173,
        3.59381366,  3.67837977,  3.76493581,  3.85352859,  3.94420606,
        4.03701726,  4.1320124 ,  4.22924287,  4.32876128,  4.43062146,
        4.53487851,  4.64158883,  4.75081016,  4.86260158,  4.97

In [35]:
arr2d = np.zeros((5,5))

In [36]:
arr2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
cubo = np.zeros((5,5,5)).astype(int)+1

In [38]:
cubo

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [ ]:
cubo = np.ones((5,5,5)).astype(np.float16)

In [ ]:
cubo

In [ ]:
cubo.dtype

In [ ]:
np.empty((2,3,4))

<div class="alert alert-danger">
**PELIGRO**

¡`np.empty` no devuelve un arreglo de ceros!
</div>

In [ ]:
np.eye(4)

In [ ]:
np.random.rand(3)

## Reshaping

In [ ]:
arr = np.arange(1000)

In [ ]:
arr3d = arr.reshape((10,10,10))

In [ ]:
arr3d.ndim

In [ ]:
arr3d.shape

In [ ]:
arr3d

In [ ]:
arr = np.arange(200)

In [ ]:
arr2d = arr.reshape((10,20))

In [ ]:
arr2d

## Aplanar

In [ ]:
arr = np.zeros((4,4,4,4))

In [ ]:
arr.shape

In [ ]:
arr_plano = arr.ravel()

In [ ]:
arr_plano.shape

## *Broadcasting*

In [ ]:
data = np.array([1,2,3,4,5])

In [ ]:
data

In [ ]:
data + 1

In [ ]:
data * 2

In [ ]:
data ** 2

## Transponer

In [ ]:
arr = np.arange(15).reshape((3,5))

In [ ]:
arr

In [ ]:
arr.T

¿Qué pasa en varias dimensiones?

In [ ]:
arr  = np.arange(16).reshape((2,2,4))

In [ ]:
arr

In [ ]:
arr.transpose((1,0,2))

`transpose` recibe una `tupla` de los índices de los ejes y los permuta. `(O_o)`

<div class="alert alert-info">
**Ejercicio** Diseña un ejemplo multidimensional, donde sea obvia la permutación
</div>

## Slicing e Indexado

En el ejercicio vimos que el indexado en `arrays` de 1D es igual que el indexado y *slicing* de las listas de python. ¿Pero que sucede en $n-$dimensiones?

### Cuidado al hacer *slicing*

In [ ]:
arr = np.arange(10)

In [ ]:
arr

El _slincing_ genera (devuelve) una **vista**, si modificas el =array= original, la **vista** se ve modificada también.

In [ ]:
arr_slice =  arr[5:8]

In [ ]:
arr_slice

In [ ]:
arr_slice[1]= 12345678

In [ ]:
arr_slice

In [ ]:
arr

In [ ]:
arr_slice[:] = 345

In [ ]:
arr_slice

In [ ]:
arr

In [ ]:
arr2 = np.copy(arr)

In [ ]:
arr2

In [ ]:
arr2[5:8] = [5,6,7]

In [ ]:
arr2

In [ ]:
arr

In [ ]:
np.may_share_memory(arr, arr_slice)

In [ ]:
np.may_share_memory(arr, arr2)

### Multidimensional

In [ ]:
arr = np.arange(9)

In [ ]:
arr.shape = (3,3)

In [ ]:
arr

In [ ]:
arr.ndim

In [ ]:
arr[2]

In [ ]:
arr[-1]

In [ ]:
arr[1][1]

In [ ]:
arr[1:]

In [ ]:
arr[:2]

In [ ]:
arr[:1,:2]

In [ ]:
arr[1:,:2]

In [ ]:
arr[1,]

In [ ]:
arr[1,:2]

In [ ]:
arr[1,2:]

In [ ]:
arr[:,1:]

In [ ]:
arr[:,:1]

<div class="alert alert-info">
**Ejercicio**:

Explique como funciona el *slicing* $n$-dimensional.
</div>

In [ ]:
arr

In [ ]:
index = arr > 2

In [ ]:
index

In [ ]:
arr[index]

In [ ]:
arr2 = arr[index]

In [ ]:
arr

In [ ]:
arr2

<div class="alert alert-info">
**Ejercicio:**
(a) Cree un arreglo de 2D $5\times5$ lleno de unos. (b) Utilice *slicing* para seleccionar 1 cuadrado alrededor del centro  y llénelo con $2$s.  (c) Utilice *slicing* para seleccionar  el centro y asígnele $4$. (d) Copie el arreglo. (e) Utilice *slicing* lógico para seleccionar el cuadro interno y asígnele cero. (f) En el cuadro copiado, al centro y al cuadro exterior asígnele $0$.
</div>

## Fancy Indexing

In [ ]:
arr = np.ones((5,4))

In [ ]:
for i in range(5):
    arr[i] = i

In [ ]:
arr

In [ ]:
arr[[4,3,1,2]]

In [ ]:
arr[[-3,-2,-1]]

¿Puedes explicar que hace el _fancy indexing_?

## Funciones Universales

Las *funciones universales*  realizan operaciones elemento por elemento en los arreglos. 

In [ ]:
arr = np.arange(10)

In [ ]:
arr = -1*arr

In [ ]:
arr

In [ ]:
arr = np.abs(arr)

In [ ]:
arr

In [ ]:
np.sqrt(arr)

In [ ]:
np.sign(arr)

In [ ]:
np.isfinite(arr)

In [ ]:
np.logical_not(arr)

In [ ]:
arr

In [ ]:
arr = np.random.randn(10)

In [ ]:
arr

In [ ]:
np.ceil(arr)

In [ ]:
np.floor(arr)

In [ ]:
np.rint(arr)

In [ ]:
arr2 = np.ones(10)

In [ ]:
np.add(arr, arr2)

In [ ]:
np.multiply(arr, arr2)

In [ ]:
np.maximum(arr, arr2)

In [ ]:
np.logical_and(arr, arr2)

## Agregaciones

Funciones que calculan operaciones a lo largo de un eje.

In [ ]:
arr

In [ ]:
arr.sum()

In [ ]:
arr.mean()

In [ ]:
arr = np.random.randn(5,4)

In [ ]:
arr

In [ ]:
arr.sum()

In [ ]:
arr.mean()

In [ ]:
arr.sum(0)

In [ ]:
arr = np.arange(10)

In [ ]:
arr.cumsum()

In [ ]:
arr.cumprod()

In [ ]:
arr.reshape(2,5)

In [ ]:
arr.cumsum()

In [ ]:
arr > 5

In [ ]:
(arr > 5).sum()

## Operaciones de conjuntos

In [ ]:
arr

In [ ]:
arr2

In [ ]:
np.unique(arr2)

In [ ]:
np.intersect1d(arr, arr2)

<div class="alert alert-info">
**Ejercicio** Usando la definición de [**cuadrados mágicos**](http://en.wikipedia.org/wiki/Magic_square) crea una función que reciba un arreglo e indique si es o no un cuadrado mágico.
</div>

## Casting

In [ ]:
a = np.array([1,2,3])
a

El tipo de mayor jerarquía define el _cast_

In [ ]:
a + 1.5

La asignación **no** cambia el tipo del arreglo.

In [ ]:
a.dtype

In [ ]:
(a + 1.5).dtype

## Tipos 

In [ ]:
np.iinfo(np.int)   # Prueba con 8, 16, 32 y 64 bits

<div class="alert alert-info">
**Ejercicio** ¿Qué pasa con `int`?
</div>

In [ ]:
np.finfo(np.float64)

In [ ]:
np.finfo(np.float64).eps

In [ ]:
np.float32(1e-8) + np.float32(1) == 1

In [ ]:
np.float64(1e-8) + np.float64(1) == 1

## Estructura de datos

In [ ]:
muestra = np.zeros((6,), dtype=[('codigo', 'S4'),('posicion', float), ('valor', float)])

In [ ]:
muestra

In [ ]:
muestra.ndim

In [ ]:
muestra.shape

In [ ]:
muestra.dtype.names

In [ ]:
muestra[:] = [('ALFA',   1, 0.37), ('BETA', 1, 0.11), ('TAU', 1,   0.13),('ALFA', 1.5, 0.37), ('ALFA', 3, 0.11), ('TAU', 1.2, 0.13)]

In [ ]:
muestra

In [ ]:
muestra.shape

In [ ]:
muestra['codigo']

In [ ]:
muestra[0]['valor']

In [ ]:
muestra[['codigo', 'valor']]

In [ ]:
muestra[muestra['codigo'] == 'ALFA']

## Broadcasting (Segunda vuelta)

<div class="alert alert-warning">
**NOTA** Las imágenes y ejemplos están basados en la presentación  **The NumPy Array: A Structure for
Efficient Numerical Computation** de _Stéfan van der Walt_ de 2010.
</div>

### 1D

<img src="images/broadcasting_1d.png"/>

In [ ]:
x = np.arange(4)
x

In [ ]:
x + 3

### 2D

<img src="images/broadcasting_2d.png"/>

In [ ]:
a = np.arange(12).reshape((3,4))
print( a.shape)
a

In [ ]:
b = np.array([1,2,3])
print( b.shape)
b

In [ ]:
a+b

<div class="alert alert-danger">
**Observa muy bien lo que acaba de pasar, el error es a propósito...**
</div>

In [ ]:
b = b[:, np.newaxis]
print (b.shape)
b

In [ ]:
a + b