# Introducción

**NumPy** es la *librería* de python para computación científica. **NumPy** agrega al lenguaje lo siguiente: Arreglos multidimensionales, operaciones elemento por elemento (técnica conocida como *broadcasting*), algebra lineal, manipulación de imágenes, la habilidad de utilizar código `C/C++` y `FORTRAN`, entre muchas otras.

La mayor parte de los componentes del sistema de computo científico de Python, están construidas encima de **NumPy**, un ejemplo que veremos en el curso es `SciPy`.

Para poder utilizar **NumPy**, es necesario importarlo a la sesión del `notebook`.

### Bibliografía de soporte

- *NumPy Beginner's Guide* _Ivan Idris_,  PACKT Publishing, 2012
- *NumPy Cookbook* _Ivan Idris_, PACKT Publishing, 2012
- *Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython*, _Wes McKinney_, O'REILLY, 2012

In [137]:
import numpy as np

## Arrays

El principal componente de **NumPy** es el `array`, el cual es una versión más poderosa, pero menos flexible que las listas de python.

In [138]:
lst =  [1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [139]:
#Creando un arreglo

arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [140]:
lst[2:3]

[3]

In [141]:
arr[2:3]

array([3])

<div class="alert alert-info">
**Ejercicio:** Repite los ejercicios de listas del *Lecture 2* con `array`.
</div>

In [142]:
lst[-1] = "Las listas pueden tener varios tipos de datos"
lst

[1, 2, 3, 4, 'Las listas pueden tener varios tipos de datos']

In [143]:
#Los arreglos no admiten este tipo de datos

arr[-1] = "Los arreglos no..."

ValueError: invalid literal for int() with base 10: 'Los arreglos no...'

Una vez inicializado el `array` sólo puede contener un tipo de dato.

In [292]:
#Tipo de dato del arreglo

arr.dtype

dtype('int64')

In [293]:
# Aunque le metas un flotante lo vuelve entero porque ese tipo de dato es el arreglo

arr[-1] = 1.23456
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 1])

In [294]:
arr.dtype

dtype('int64')

Sacrificamos la versatilidad de las listas por velocidad. Creeemos un `array` de 1 millón de elementos y multiplicaremos cada uno de ellos por una constante (*broadcasting*).

In [295]:
#Aquí estamos viendo un arreglo de 10000000 entradas

arr = np.arange(1e7)  

In [296]:
#aquí en un dos por tres convierte el arreglo en lista 

lst = arr.tolist()

Las listas no soportan *broadcasting* por lo que crearemos una función que lo simule

In [297]:
def lst_multiplicacion( alist , scalar ): 
    for i , val in enumerate ( alist ): 
        alist [ i ] = val
    return alist

In [298]:
%timeit arr * 1.1


#Medimos el tiempo que tarda la compu para multiplicar todas las entradas por 1.1

334 ms ± 38.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [299]:
%timeit lst_multiplicacion(lst, 1.1)

#MEDIMOS EL TIEMPO QUE TARDA LA COMPU PARA HACERLO EN UNA LISTA Y PS TARDA MUCHO

2.54 s ± 405 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Creación de arrays

In [300]:
arr = np.array([1,2,3,4,5])

In [301]:
arr

array([1, 2, 3, 4, 5])

In [302]:
arr = np.arange(10,21)

#Generas un arreglo de un rango de 10 a 20

In [303]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [304]:
arr = np.zeros(5)

#Arreglo de 5 ceros

In [305]:
arr

array([0., 0., 0., 0., 0.])

In [306]:
arr = np.linspace(0,1,100)

#Aquí estamos viendo que la imagen es de cero a uno, hace una partición de esa imagen, son 100 partes. 
#Luego lo evalua en una función lineal

In [307]:
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [146]:
arr = np.logspace(0,1,100, base=10)

#Aquí lo que estamos haciendo es darle la imagen. Busca el valor donde el logb10 vale cero y donde vale 1, la preimagen de ese intervalo
# lo divde en 100, luego lo evalúa y lo que te regresa es la imagen.

In [147]:
arr

array([ 1.        ,  1.02353102,  1.04761575,  1.07226722,  1.09749877,
        1.12332403,  1.149757  ,  1.17681195,  1.20450354,  1.23284674,
        1.26185688,  1.29154967,  1.32194115,  1.35304777,  1.38488637,
        1.41747416,  1.45082878,  1.48496826,  1.51991108,  1.55567614,
        1.59228279,  1.62975083,  1.66810054,  1.70735265,  1.7475284 ,
        1.78864953,  1.83073828,  1.87381742,  1.91791026,  1.96304065,
        2.009233  ,  2.05651231,  2.10490414,  2.15443469,  2.20513074,
        2.25701972,  2.3101297 ,  2.36448941,  2.42012826,  2.47707636,
        2.53536449,  2.59502421,  2.65608778,  2.71858824,  2.7825594 ,
        2.84803587,  2.91505306,  2.98364724,  3.05385551,  3.12571585,
        3.19926714,  3.27454916,  3.35160265,  3.43046929,  3.51119173,
        3.59381366,  3.67837977,  3.76493581,  3.85352859,  3.94420606,
        4.03701726,  4.1320124 ,  4.22924287,  4.32876128,  4.43062146,
        4.53487851,  4.64158883,  4.75081016,  4.86260158,  4.97

In [148]:
arr2d = np.zeros((5,5))

In [149]:
arr2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [150]:
cubo = np.zeros((5,5,5)).astype(int)+1

#Hace una matriz de ceros con tipo int y le suma 1 a cada entrada

In [151]:
cubo

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [152]:
cubo = np.ones((5,5,5)).astype(np.float16)

# Matriz de unos de tipo flotante

In [153]:
cubo

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float16)

In [154]:
cubo.dtype

dtype('float16')

In [155]:
np.empty((2,3,4))

array([[[4.64484663e-310, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000]]])

<div class="alert alert-danger">
**PELIGRO**

¡`np.empty` no devuelve un arreglo de ceros!
</div>

In [308]:
#Genera la matriz identidad de 4x4 

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [309]:
#También agrega renglones o columnas de ceros si la mtriz no es cuadrada 

np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [311]:
np.eye(6,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [157]:
np.random.rand(3)

#Vector de numeros aleatorios

array([0.78852784, 0.13858701, 0.74108599])

## Reshaping

In [158]:
arr = np.arange(1000)

In [159]:
arr3d = arr.reshape((10,10,10))

#Le cambia las dimensiones 

#En este caso, 10 columnas, 10 filas y 10 de profundidad

In [160]:
arr3d.ndim

3

In [161]:
arr3d.shape

(10, 10, 10)

In [162]:
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [163]:
arr = np.arange(200)

In [164]:
arr2d = arr.reshape((10,20))

In [165]:
arr2d

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
         33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 1

## Aplanar

In [312]:
arr = np.zeros((4,4,4,4))
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

      

In [167]:
arr.shape

(4, 4, 4, 4)

In [168]:
arr_plano = arr.ravel()

In [313]:
arr_plano  #Pues lo vuelve un vector y ya, bye

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [169]:
arr_plano.shape

(256,)

## *Broadcasting*

In [170]:
data = np.array([1,2,3,4,5])

In [171]:
data

array([1, 2, 3, 4, 5])

In [172]:
#Sumandole 1 a todas las entradas
data + 1

array([2, 3, 4, 5, 6])

In [173]:
data * 2

#Multiplicando por dos las entradas

array([ 2,  4,  6,  8, 10])

In [174]:
data ** 2

#Elevando al cuadrado las entradas

array([ 1,  4,  9, 16, 25])

## Transponer

In [175]:
arr = np.arange(15).reshape((3,5))

In [176]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [177]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

¿Qué pasa en varias dimensiones?

In [178]:
arr  = np.arange(16).reshape((2,2,4))

In [179]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [180]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

`transpose` recibe una `tupla` de los índices de los ejes y los permuta. `(O_o)`

<div class="alert alert-info">
**Ejercicio** Diseña un ejemplo multidimensional, donde sea obvia la permutación
</div>

## Slicing e Indexado

En el ejercicio vimos que el indexado en `arrays` de 1D es igual que el indexado y *slicing* de las listas de python. ¿Pero que sucede en $n-$dimensiones?

### Cuidado al hacer *slicing*

In [181]:
arr = np.arange(10)

In [182]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

El _slincing_ genera (devuelve) una **vista**, si modificas el =array= original, la **vista** se ve modificada también.

In [183]:
arr_slice =  arr[5:8]

In [184]:
arr_slice

array([5, 6, 7])

In [185]:
arr_slice[1]= 12345678

In [186]:
arr_slice

array([       5, 12345678,        7])

In [187]:
arr

array([       0,        1,        2,        3,        4,        5,
       12345678,        7,        8,        9])

In [188]:
arr_slice[:] = 345

In [189]:
arr_slice

array([345, 345, 345])

In [190]:
arr

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [191]:
arr2 = np.copy(arr)

In [192]:
arr2

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [193]:
arr2[5:8] = [5,6,7]

In [194]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [195]:
arr

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [196]:
np.may_share_memory(arr, arr_slice)


#Acaso comparten memoria estas weas? si

True

In [197]:
np.may_share_memory(arr, arr2)

False

### Multidimensional

In [198]:
arr = np.arange(9)

In [199]:
arr.shape = (3,3)

In [200]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [201]:
arr.ndim

2

In [202]:
arr[2]

array([6, 7, 8])

In [203]:
arr[-1]

array([6, 7, 8])

In [204]:
arr[1][1]

4

In [205]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [206]:
arr[:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [207]:
arr[:1,:2]

array([[0, 1]])

In [208]:
arr[1:,:2]

array([[3, 4],
       [6, 7]])

In [209]:
arr[1,]

array([3, 4, 5])

In [210]:
arr[1,:2]

array([3, 4])

In [211]:
arr[1,2:]

array([5])

In [212]:
arr[:,1:]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [213]:
arr[:,:1]

array([[0],
       [3],
       [6]])

<div class="alert alert-info">
**Ejercicio**:

Explique como funciona el *slicing* $n$-dimensional.
</div>

In [214]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [215]:
index = arr > 2

In [216]:
index

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [217]:
arr[index]

array([3, 4, 5, 6, 7, 8])

In [218]:
arr2 = arr[index]

In [219]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [220]:
arr2

array([3, 4, 5, 6, 7, 8])

<div class="alert alert-info">
**Ejercicio:**
(a) Cree un arreglo de 2D $5\times5$ lleno de unos. (b) Utilice *slicing* para seleccionar 1 cuadrado alrededor del centro  y llénelo con $2$s.  (c) Utilice *slicing* para seleccionar  el centro y asígnele $4$. (d) Copie el arreglo. (e) Utilice *slicing* lógico para seleccionar el cuadro interno y asígnele cero. (f) En el cuadro copiado, al centro y al cuadro exterior asígnele $0$.
</div>

## Fancy Indexing

In [221]:
arr = np.ones((5,4))

In [222]:
for i in range(5):
    arr[i] = i

In [223]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [224]:
arr[[4,3,1,2]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.]])

In [225]:
arr[[-3,-2,-1]]

array([[2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

¿Puedes explicar que hace el _fancy indexing_?

## Funciones Universales

Las *funciones universales*  realizan operaciones elemento por elemento en los arreglos. 

In [226]:
arr = np.arange(10)

In [227]:
arr = -1*arr

In [228]:
arr

array([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [229]:
arr = np.abs(arr)

In [230]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [231]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [232]:
np.sign(arr)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [233]:
np.isfinite(arr)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [234]:
#Cualquier número que no sea cero es verdadero. Logical not lo que hace es pues negar eso, alv

np.logical_not(arr)

array([ True, False, False, False, False, False, False, False, False,
       False])

In [235]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [236]:
arr = np.random.randn(10)

In [237]:
arr

array([-1.89328389,  1.92002114, -0.39215055,  0.13486676, -2.17102505,
       -0.77306282,  1.20457509, -1.61755406, -0.28524057, -0.93750099])

In [238]:
#Función techo en cada elemento del arreglo

np.ceil(arr)

array([-1.,  2., -0.,  1., -2., -0.,  2., -1., -0., -0.])

In [239]:
#Función piso del arreglo

np.floor(arr)

array([-2.,  1., -1.,  0., -3., -1.,  1., -2., -1., -1.])

In [240]:
arr

array([-1.89328389,  1.92002114, -0.39215055,  0.13486676, -2.17102505,
       -0.77306282,  1.20457509, -1.61755406, -0.28524057, -0.93750099])

In [241]:
#Redondeo, jsjs

np.rint(arr)

array([-2.,  2., -0.,  0., -2., -1.,  1., -2., -0., -1.])

In [242]:
arr2 = np.ones(10)

In [243]:
#Suma de arrays

np.add(arr, arr2)

array([-0.89328389,  2.92002114,  0.60784945,  1.13486676, -1.17102505,
        0.22693718,  2.20457509, -0.61755406,  0.71475943,  0.06249901])

In [244]:
#Multiplicación de arreglos 

np.multiply(arr, arr2)

array([-1.89328389,  1.92002114, -0.39215055,  0.13486676, -2.17102505,
       -0.77306282,  1.20457509, -1.61755406, -0.28524057, -0.93750099])

In [245]:
#Obtiene el máximo de entre los dos 

np.maximum(arr, arr2)

array([1.        , 1.92002114, 1.        , 1.        , 1.        ,
       1.        , 1.20457509, 1.        , 1.        , 1.        ])

In [246]:
#Ve si los dos son distintos de cero o así 

np.logical_and(arr, arr2)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## Agregaciones

Funciones que calculan operaciones a lo largo de un eje.

In [247]:
#Recuerda que esto es un arreglo de un reglón con una columna

arr

array([-1.89328389,  1.92002114, -0.39215055,  0.13486676, -2.17102505,
       -0.77306282,  1.20457509, -1.61755406, -0.28524057, -0.93750099])

In [248]:
#Suma todas las entradas

arr.sum()

-4.810354930964169

In [249]:
#Le saca el promedio a todas las entradas

arr.mean()

-0.4810354930964169

In [250]:
arr = np.random.randn(5,4)

In [251]:
arr

array([[-2.05209553, -2.43263824, -0.84085664,  0.49502999],
       [ 1.30581424, -0.93205695, -0.28158126,  2.09264942],
       [-2.08094547,  0.39892709, -2.23605818, -1.31280095],
       [ 0.80305656, -0.20513155, -1.96135624, -0.39790264],
       [-0.59978089, -0.91677155, -1.06606357,  2.31769334]])

In [252]:
#Suma todas las entradas de las matrices

arr.sum()

-9.90286903281396

In [253]:
#Esto hace todo el promedio de todas las entradas de la matriz 

arr.mean()

-0.495143451640698

In [254]:
#Aquí está sumando todas las columnas con el renglón cero 

arr.sum(0)

array([-2.6239511 , -4.0876712 , -6.38591589,  3.19466916])

In [255]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [256]:
#Suma acumuladaa


arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [257]:
#Producto acumulado

arr.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [258]:
arr2 = arr.reshape(2,5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [259]:
arr2.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [260]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [261]:
# ¿Te dice cuantos numeros son mayores a 5?

(arr > 5).sum()

4

## Operaciones de conjuntos

In [262]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [325]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 1]])

In [326]:
np.unique(arr2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [322]:
arr2[0][3]=3
#arr2

In [327]:
#La intersección entre dos arreglos
np.intersect1d(arr, arr2)

array([0.])

<div class="alert alert-info">
**Ejercicio** Usando la definición de [**cuadrados mágicos**](http://en.wikipedia.org/wiki/Magic_square) crea una función que reciba un arreglo e indique si es o no un cuadrado mágico.
</div>

## Casting

In [266]:
a = np.array([1,2,3])
a

array([1, 2, 3])

El tipo de mayor jerarquía define el _cast_

In [267]:
a + 1.5

array([2.5, 3.5, 4.5])

La asignación **no** cambia el tipo del arreglo.

In [268]:
a.dtype

dtype('int64')

In [269]:
(a + 1.5).dtype

dtype('float64')

## Tipos 

In [270]:
#Te dice el mayor o menor numero que puedes escribir con 8,16,31 y 64 bits


np.iinfo(np.int64)   # Prueba con 8, 16, 32 y 64 bits

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

<div class="alert alert-info">
**Ejercicio** ¿Qué pasa con `int`?
</div>

In [271]:
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [272]:
np.finfo(np.float64).eps

2.220446049250313e-16

In [273]:
np.float32(1e-8) + np.float32(1) == 1

True

In [274]:
np.float64(1e-8) + np.float64(1) == 1

False

## Estructura de datos

In [275]:
muestra = np.zeros((6,), dtype=[('codigo', 'S4'),('posicion', float), ('valor', float)])

In [276]:
muestra

array([(b'', 0., 0.), (b'', 0., 0.), (b'', 0., 0.), (b'', 0., 0.),
       (b'', 0., 0.), (b'', 0., 0.)],
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

In [277]:
muestra.ndim

1

In [278]:
muestra.shape

(6,)

In [279]:
muestra.dtype.names

('codigo', 'posicion', 'valor')

In [280]:
muestra[:] = [('ALFA',   1, 0.37), ('BETA', 1, 0.11), ('TAU', 1,   0.13),('ALFA', 1.5, 0.37), ('ALFA', 3, 0.11), ('TAU', 1.2, 0.13)]

In [281]:
muestra

array([(b'ALFA', 1. , 0.37), (b'BETA', 1. , 0.11), (b'TAU', 1. , 0.13),
       (b'ALFA', 1.5, 0.37), (b'ALFA', 3. , 0.11), (b'TAU', 1.2, 0.13)],
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

In [282]:
muestra.shape

(6,)

In [283]:
muestra['codigo']

array([b'ALFA', b'BETA', b'TAU', b'ALFA', b'ALFA', b'TAU'], dtype='|S4')

In [284]:
muestra[0]['valor']

0.37

In [285]:
muestra[['codigo', 'valor']]

array([(b'ALFA', 0.37), (b'BETA', 0.11), (b'TAU', 0.13), (b'ALFA', 0.37),
       (b'ALFA', 0.11), (b'TAU', 0.13)],
      dtype={'names':['codigo','valor'], 'formats':['S4','<f8'], 'offsets':[0,12], 'itemsize':20})

In [286]:
#inteto de filtrar el arreglo, jsjs

muestra[muestra['codigo'] == 'ALFA']

array([], shape=(0, 6),
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

## Broadcasting (Segunda vuelta)

<div class="alert alert-warning">
**NOTA** Las imágenes y ejemplos están basados en la presentación  **The NumPy Array: A Structure for
Efficient Numerical Computation** de _Stéfan van der Walt_ de 2010.
</div>

### 1D

<img src="images/broadcasting_1d.png"/>

In [287]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [288]:
x + 3

array([3, 4, 5, 6])

### 2D

<img src="images/broadcasting_2d.png"/>

In [289]:
a = np.arange(12).reshape((3,4))
print( a.shape)
a

(3, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [290]:
b = np.array([1,2,3])
print( b.shape)
b

(3,)


array([1, 2, 3])

In [291]:
a+b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

<div class="alert alert-danger">
**Observa muy bien lo que acaba de pasar, el error es a propósito...**
</div>

In [ ]:
b = b[:, np.newaxis]
print (b.shape)
b

In [ ]:
a + b