# Ejercicios de NumPy 

In [1]:
%pylab inline
import math
import numpy as np

Populating the interactive namespace from numpy and matplotlib


## Pregunta 4

El **Sudoku** es un pasatiempo que consiste en un arreglo  $9 \times 9$ de celdas, con dígitos del 1 al 9, de tal manera que no se repiten valores en cada columna, cada renglón y en cada subarreglo de $3\times 3$.

(a) Crea una función llamada `correcto` que reciba un `array` $1d$ de tamaño 9 e indique si está completo o no (i.e. incluye los números del 1 al 9.

In [41]:
def correcto(arreglo):
    if len(arreglo) == 9:
        for i in range(1,10):
            if i not in arreglo:
                return 'No contiene range(1,10)'
        return 'True'
    else:
        return 'No tiene el tamaño adecuado'

In [42]:
arreglo = np.arange(1,10)
arreglo1 = np.arange(3,12)
arreglo2 = np.arange(5,100)

print(correcto(arreglo))
print(correcto(arreglo1))
print(correcto(arreglo2))

True
No contiene range(1,10)
No tiene el tamaño adecuado


(b) Crea una función llamada `descomponer3x3` que reciba un `array` de enteros de $9\times 9$ y lo separe en sus 9 subarreglos $3\times3$.

In [4]:
def descomponer3x3(arreglo): 
    desarreglo = np.reshape(arreglo,(9,3,3))
    return desarreglo

### Programa para hacer listas random de sudoku 9x9

In [5]:
# Hacemos un range(0,9) y lo shuffleamos, así 9 veces. Esto terminó siendo más fácil que 
# crear 9 elementos random entre (0,9) y checar que ninguno estuviera repetido. Y que si sí estaba repetido
# que lo sustituyera. Siempre me marcó error.

sudok = []
for i in range(0,9):
    lista = list(range(1,10)) 
    random.shuffle(lista)
    sudok.append(lista)
sudoku = array(sudok)

print(sudoku)

[[6 8 3 2 4 9 5 7 1]
 [1 8 4 7 9 3 5 6 2]
 [5 9 2 7 3 8 1 4 6]
 [7 5 2 1 9 3 6 8 4]
 [1 7 9 2 6 3 4 5 8]
 [8 9 4 3 6 2 5 7 1]
 [3 1 4 2 6 5 9 8 7]
 [2 6 4 1 3 7 8 5 9]
 [6 4 9 7 1 2 3 5 8]]


In [6]:
descomponer3x3(sudoku)

array([[[6, 8, 3],
        [2, 4, 9],
        [5, 7, 1]],

       [[1, 8, 4],
        [7, 9, 3],
        [5, 6, 2]],

       [[5, 9, 2],
        [7, 3, 8],
        [1, 4, 6]],

       [[7, 5, 2],
        [1, 9, 3],
        [6, 8, 4]],

       [[1, 7, 9],
        [2, 6, 3],
        [4, 5, 8]],

       [[8, 9, 4],
        [3, 6, 2],
        [5, 7, 1]],

       [[3, 1, 4],
        [2, 6, 5],
        [9, 8, 7]],

       [[2, 6, 4],
        [1, 3, 7],
        [8, 5, 9]],

       [[6, 4, 9],
        [7, 1, 2],
        [3, 5, 8]]])

(c) Crea la función `esSolucion` que recibe un `array` de $9\times 9$ y devuelve si es o no solución del sudoku.

<img src="Data/sudoku-principles.png"/>

In [43]:
def esSolucion(sudoku):
    
    # En estas listas se meterán los valores de las columnas, filas y cuadrados
    # después de haber sido evaluados en la función correcto
    
    f = []    
    c = []
    cuadros = []
    
    # En las listas presentadas primero se toman las primeras 3 filas y se meten los primeros 3 elementos a l1.
    # Después se toman los elementos de cada elemento de la lista l1 y se meten a l11
    # (Esto lo hice ya que, al hacer la lista l1, se guardaban los elemntos como array. 
    # Fue lo único que se me ocurrió)
    # En la lista l11 ya tenemos los elementos tenemos que revisar de cada cuadrante con la función correcto. 
    # Imprimimos cada fila lii que se checa y el resultado al aplicar a ese elemento la función correcto.
    # Como en la imagen, tenemos que checar que en el cuadrante (R1,R3) x (C1,C3) la función correcto

    print('\n')    
    print('Cuadrantes')
    print('\n')
    

    l1 = []
    l11 = []

    for i in range(0,3):
        l1.append(sudoku[i][0:3])
    for k in range(0,3):
        for j in l1:
            l11.append(j[k])
    
    cuadros.append(correcto(l11))
    print(l11) 
    print(correcto(l11))
        
    
    l2 = []
    l22 = []

    for i in range(0,3):
        l2.append(sudoku[i][3:6])
    for k in range(0,3):
        for j in l2:
            l22.append(j[k])

    cuadros.append(correcto(l22))
    print(l22)     
    print(correcto(l22))
    
    l3 = []
    l33 = []

    for i in range(0,3):
        l3.append(sudoku[i][6:])
    for k in range(0,3):
        for j in l3:
            l33.append(j[k])

    cuadros.append(correcto(l33))
    print(l33)  
    print(correcto(l33))
    
    #Ahora se toman del renglón 3 al 6
    
    l4 = []
    l44 = []

    for i in range(3,6):
        l4.append(sudoku[i][0:3])
    for k in range(0,3):
        for j in l4:
            l44.append(j[k])

    cuadros.append(correcto(l44))
    print(l44)   
    print(correcto(l44))

    l5 = []
    l55 = []

    for i in range(3,6):
        l5.append(sudoku[i][3:6])
    for k in range(0,3):
        for j in l5:
            l55.append(j[k])

    cuadros.append(correcto(l55))
    print(l55)   
    print(correcto(l55))
    
    l6 = []
    l66 = []

    for i in range(3,6):
        l6.append(sudoku[i][6:])
    for k in range(0,3):
        for j in l6:
            l66.append(j[k])
    
    cuadros.append(correcto(l66))
    print(l66) 
    print(correcto(l66))

       #Ahora se toman del renglón 7 al 9
    
    l7 = []
    l77 = []

    for i in range(6,9):
        l7.append(sudoku[i][0:3])
    for k in range(0,3):
        for j in l7:
            l77.append(j[k])

    cuadros.append(correcto(l77))
    print(l77) 
    print(correcto(l77))

    l8 = []
    l88 = []

    for i in range(6,9):
        l8.append(sudoku[i][3:6])
    for k in range(0,3):
        for j in l8:
            l88.append(j[k])

    cuadros.append(correcto(l88))
    print(l88)
    print(correcto(l88))

    l9 = []
    l99 = []

    for i in range(6,9):
        l9.append(sudoku[i][6:])
    for k in range(0,3):
        for j in l9:
            l99.append(j[k])

    cuadros.append(correcto(l99))
    print(l99)   
    print(correcto(l99))
    
    # Checamos ahora que cada fila del sudoku cumpla con la función correcto 
    
    print('\n')    
    print('Filas')
    print('\n')
    
    for i in sudoku:
        print(i)
        print(correcto(i))
        f.append(correcto(i))
        
        # Metemos el resultado de correcto en la lista de las filas
        # Imprimimos cada fila que se checa y el resultado de correcto
            
    print('\n')
    print('Columnas')
    print('\n')
    
    # Checamos que toda columna en la lista 'sudoku' cumpla la función correcto
    
    for i in range(9):
        print((sudoku[:,i]))
        print(correcto(sudoku[:,i]))
        c.append(correcto(sudoku[:,i]))

    # Metemos el resultado de correcto en la lista de las columnas
    # Imprimimos cada columna que se checa y el resultado de correcto

    zipped = list(zip(cuadros, c, f))
    
    #Hacemos un zip, ya que bastará que una de las entradas sea distinta a 'True' para que no sea solución
    
    print('\n')

    ultimatum = [(i,j,k) for (i,j,k) in zipped if (i,j,k) != ('True', 'True', 'True')]
    check = []
    
    if ultimatum == check:
        return 'Es solución'
    else: 
        return 'No es solución'
        

In [44]:
esSolucion(sudoku)



Cuadrantes


[6, 1, 5, 8, 8, 9, 3, 4, 2]
No contiene range(1,10)
[2, 7, 7, 4, 9, 3, 9, 3, 8]
No contiene range(1,10)
[5, 5, 1, 7, 6, 4, 1, 2, 6]
No contiene range(1,10)
[7, 1, 8, 5, 7, 9, 2, 9, 4]
No contiene range(1,10)
[1, 2, 3, 9, 6, 6, 3, 3, 2]
No contiene range(1,10)
[6, 4, 5, 8, 5, 7, 4, 8, 1]
No contiene range(1,10)
[3, 2, 6, 1, 6, 4, 4, 4, 9]
No contiene range(1,10)
[2, 1, 7, 6, 3, 1, 5, 7, 2]
No contiene range(1,10)
[9, 8, 3, 8, 5, 5, 7, 9, 8]
No contiene range(1,10)


Filas


[6 8 3 2 4 9 5 7 1]
True
[1 8 4 7 9 3 5 6 2]
True
[5 9 2 7 3 8 1 4 6]
True
[7 5 2 1 9 3 6 8 4]
True
[1 7 9 2 6 3 4 5 8]
True
[8 9 4 3 6 2 5 7 1]
True
[3 1 4 2 6 5 9 8 7]
True
[2 6 4 1 3 7 8 5 9]
True
[6 4 9 7 1 2 3 5 8]
True


Columnas


[6 1 5 7 1 8 3 2 6]
No contiene range(1,10)
[8 8 9 5 7 9 1 6 4]
No contiene range(1,10)
[3 4 2 2 9 4 4 4 9]
No contiene range(1,10)
[2 7 7 1 2 3 2 1 7]
No contiene range(1,10)
[4 9 3 9 6 6 6 3 1]
No contiene range(1,10)
[9 3 8 3 3 2 5 7 2]
No contiene range(1,10)
[5 5 

'No es solución'

In [45]:
# Otro que no es solución, sí tiene correctas las columnas, pero no están bien los cuadrantes
sudoku1 = array([[1,2,3,4,5,6,7,8,9],
               [2,3,4,5,6,7,8,9,1],
               [3,4,5,6,7,8,9,1,2],
               [4,5,6,7,8,9,1,2,3],
               [5,6,7,8,9,1,2,3,4],
               [6,7,8,9,1,2,3,4,5],
               [7,8,9,1,2,3,4,5,6],
               [8,9,1,2,3,4,5,6,7],
               [9,1,2,3,4,5,6,7,8]])

In [46]:
esSolucion(sudoku1)



Cuadrantes


[1, 2, 3, 2, 3, 4, 3, 4, 5]
No contiene range(1,10)
[4, 5, 6, 5, 6, 7, 6, 7, 8]
No contiene range(1,10)
[7, 8, 9, 8, 9, 1, 9, 1, 2]
No contiene range(1,10)
[4, 5, 6, 5, 6, 7, 6, 7, 8]
No contiene range(1,10)
[7, 8, 9, 8, 9, 1, 9, 1, 2]
No contiene range(1,10)
[1, 2, 3, 2, 3, 4, 3, 4, 5]
No contiene range(1,10)
[7, 8, 9, 8, 9, 1, 9, 1, 2]
No contiene range(1,10)
[1, 2, 3, 2, 3, 4, 3, 4, 5]
No contiene range(1,10)
[4, 5, 6, 5, 6, 7, 6, 7, 8]
No contiene range(1,10)


Filas


[1 2 3 4 5 6 7 8 9]
True
[2 3 4 5 6 7 8 9 1]
True
[3 4 5 6 7 8 9 1 2]
True
[4 5 6 7 8 9 1 2 3]
True
[5 6 7 8 9 1 2 3 4]
True
[6 7 8 9 1 2 3 4 5]
True
[7 8 9 1 2 3 4 5 6]
True
[8 9 1 2 3 4 5 6 7]
True
[9 1 2 3 4 5 6 7 8]
True


Columnas


[1 2 3 4 5 6 7 8 9]
True
[2 3 4 5 6 7 8 9 1]
True
[3 4 5 6 7 8 9 1 2]
True
[4 5 6 7 8 9 1 2 3]
True
[5 6 7 8 9 1 2 3 4]
True
[6 7 8 9 1 2 3 4 5]
True
[7 8 9 1 2 3 4 5 6]
True
[8 9 1 2 3 4 5 6 7]
True
[9 1 2 3 4 5 6 7 8]
True




'No es solución'

In [47]:
# Este sí es solución
sudoku2 = array([[1, 4, 5, 3, 2, 7, 6, 9, 8],
                [8, 3, 9, 6, 5, 4, 1, 2, 7],
                [6, 7, 2, 9, 1, 8, 5, 4, 3],
                [4, 9, 6, 1, 8, 5, 3, 7, 2],
                [2, 1, 8, 4, 7, 3, 9, 5, 6],
                [7, 5, 3, 2, 9, 6, 4, 8, 1],
                [3, 6, 7, 5, 4, 2, 8, 1, 9],
                [9, 8, 4, 7, 6, 1, 2, 3, 5],
                [5, 2, 1, 8, 3, 9, 7, 6, 4]])

In [48]:
esSolucion(sudoku2)



Cuadrantes


[1, 8, 6, 4, 3, 7, 5, 9, 2]
True
[3, 6, 9, 2, 5, 1, 7, 4, 8]
True
[6, 1, 5, 9, 2, 4, 8, 7, 3]
True
[4, 2, 7, 9, 1, 5, 6, 8, 3]
True
[1, 4, 2, 8, 7, 9, 5, 3, 6]
True
[3, 9, 4, 7, 5, 8, 2, 6, 1]
True
[3, 9, 5, 6, 8, 2, 7, 4, 1]
True
[5, 7, 8, 4, 6, 3, 2, 1, 9]
True
[8, 2, 7, 1, 3, 6, 9, 5, 4]
True


Filas


[1 4 5 3 2 7 6 9 8]
True
[8 3 9 6 5 4 1 2 7]
True
[6 7 2 9 1 8 5 4 3]
True
[4 9 6 1 8 5 3 7 2]
True
[2 1 8 4 7 3 9 5 6]
True
[7 5 3 2 9 6 4 8 1]
True
[3 6 7 5 4 2 8 1 9]
True
[9 8 4 7 6 1 2 3 5]
True
[5 2 1 8 3 9 7 6 4]
True


Columnas


[1 8 6 4 2 7 3 9 5]
True
[4 3 7 9 1 5 6 8 2]
True
[5 9 2 6 8 3 7 4 1]
True
[3 6 9 1 4 2 5 7 8]
True
[2 5 1 8 7 9 4 6 3]
True
[7 4 8 5 3 6 2 1 9]
True
[6 1 5 3 9 4 8 2 7]
True
[9 2 4 7 5 8 1 3 6]
True
[8 7 3 2 6 1 9 5 4]
True




'Es solución'