(a) Crea una función llamada `correcto` que reciba un `array` $1d$ de tamaño 9 e indique si está completo o no (i.e. incluye los números del 1 al 9.

In [15]:
import numpy as np
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [161]:
def correcto(arreglo):
    if len(arreglo) == 9:
        for i in range(1,10):
            if i not in arreglo:
                return 'No contiene range(1,10)'
        else:
            return True
    else:
        return 'No tiene el tamaño adecuado'

In [162]:
arreglo = np.arange(1,10)
arreglo1 = np.arange(3,12)
arreglo2 = np.arange(5,100)

print(correcto(arreglo))
print(correcto(arreglo1))
print(correcto(arreglo2))

True
No contiene range(1,10)
No tiene el tamaño adecuado


(b) Crea una función llamada `descomponer3x3` que reciba un `array` de enteros de $9\times 9$ y lo separe en sus 9 subarreglos $3\times3$.

In [40]:
def descomponer3x3(arreglo): 
    desarreglo = np.reshape(arreglo,(9,3,3))
    return desarreglo

In [44]:
descomponer3x3(sudoku)

array([[[4, 1, 6],
        [7, 3, 8],
        [9, 5, 2]],

       [[9, 7, 3],
        [1, 4, 2],
        [5, 6, 8]],

       [[8, 3, 4],
        [5, 9, 6],
        [2, 1, 7]],

       [[6, 3, 2],
        [8, 5, 4],
        [1, 7, 9]],

       [[5, 8, 6],
        [9, 3, 7],
        [1, 2, 4]],

       [[5, 8, 2],
        [4, 3, 6],
        [9, 7, 1]],

       [[4, 8, 6],
        [3, 5, 7],
        [2, 9, 1]],

       [[9, 1, 7],
        [5, 2, 4],
        [6, 8, 3]],

       [[4, 9, 6],
        [7, 3, 5],
        [8, 1, 2]]])

In [53]:
lv = []
for i in sudoku:
    if correcto(i) == True:
        lv.append(i)
    else:
        print('NO está correcta la fila', i)
    descomponer3x3(sudoku)
    
for i in range(9):
    correct = correcto(sudoku[:,i])
    if not correct: 
        print('no')
    
    
print(list(lv))
print(descomponer3x3(sudoku))

TypeError: list indices must be integers or slices, not tuple

In [78]:


for i in sudoku:
    if correcto(i) == True:
        correct = correcto(i)
    else:
        return False

for i in range(9):
    correct = correcto(Sudoku[i,:])
    else:
        return False
    
for i in range(9):
    correct = correcto(sudoku[i,:])
    else:
        return False



[0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8]


In [219]:
def esSolucion(sudoku):
    f = []    
    c = []
    # Notemos primero que sudoku es una lista que tiene 9 sublistas con 9 elementos cada sublista
    # Checamos primero que toda sublista en la lista 'sudoku' se cumpla la función correcto
    
    for i in sudoku:
        print(i)
        print(correcto(i))
        if correcto(i) == True:
            ok = correcto(i)
            if not ok:
                return False
    
    print('\n')
    print('Columnas')
    print('\n')
    
    # Checamos que toda columna en la lista 'sudoku' cumpla la función correcto
    
    for i in range(9):
        print((sudoku[:,i]))
        print(correcto(sudoku[:,i]))
        oka = correcto(sudoku[:,i])
        if not oka:
            return False
       


In [256]:
def esSolucion(sudoku):
    f = []    
    c = []
    # Notemos primero que sudoku es una lista que tiene 9 sublistas con 9 elementos cada sublista
    # Checamos primero que toda sublista en la lista 'sudoku' se cumpla la función correcto
    
    for i in sudoku:
        print(i)
        print(correcto(i))
        f.append(correcto(i))
            
    print('\n')
    print('Columnas')
    print('\n')
    
    # Checamos que toda columna en la lista 'sudoku' cumpla la función correcto
    
    for i in range(9):
        print((sudoku[:,i]))
        print(correcto(sudoku[:,i]))
        c.append(correcto(sudoku[:,i]))

    print('\n')
    print(c)
    print('\n')    
    print(f)
    print('\n')
    zipped = list(zip(c, f))
    print(zipped)
    
    for (i,j) in zipped:
        if (i,j) != (True,True):
            return 'No es solución'
        else:
            return 'Es solución'
        

In [257]:
sudoku =array([[5, 4, 9, 8, 7, 3, 2, 1, 6],
               [6, 1, 3, 9, 2, 5, 7, 4, 8],
               [8, 7, 2, 1, 4, 6, 3, 5, 9],
               [2, 3, 1, 5, 9, 4, 8, 6, 7],
               [4, 6, 7, 3, 8, 1, 9, 2, 5],
               [9, 5, 8, 7, 6, 2, 4, 3, 1],
               [7, 2, 5, 6, 3, 9, 1, 8, 4],
               [3, 9, 6, 4, 1, 8, 5, 7, 2],
               [1, 8, 4, 2, 5, 7, 6, 9, 3]])

In [258]:
esSolucion(sudoku)

[5 4 9 8 7 3 2 1 6]
True
[6 1 3 9 2 5 7 4 8]
True
[8 7 2 1 4 6 3 5 9]
True
[2 3 1 5 9 4 8 6 7]
True
[4 6 7 3 8 1 9 2 5]
True
[9 5 8 7 6 2 4 3 1]
True
[7 2 5 6 3 9 1 8 4]
True
[3 9 6 4 1 8 5 7 2]
True
[1 8 4 2 5 7 6 9 3]
True


Columnas


[5 6 8 2 4 9 7 3 1]
True
[4 1 7 3 6 5 2 9 8]
True
[9 3 2 1 7 8 5 6 4]
True
[8 9 1 5 3 7 6 4 2]
True
[7 2 4 9 8 6 3 1 5]
True
[3 5 6 4 1 2 9 8 7]
True
[2 7 3 8 9 4 1 5 6]
True
[1 4 5 6 2 3 8 7 9]
True
[6 8 9 7 5 1 4 2 3]
True


[True, True, True, True, True, True, True, True, True]


[True, True, True, True, True, True, True, True, True]
[(True, True), (True, True), (True, True), (True, True), (True, True), (True, True), (True, True), (True, True), (True, True)]


'Es solución'

In [217]:
sudok = []
for i in range(0,9):
    lista = list(range(1,10)) 
    random.shuffle(lista)
    sudok.append(lista)
sudoku = array(sudok)
print(sudoku)

[[2 9 8 7 3 6 1 4 5]
 [2 5 3 7 6 8 1 4 9]
 [2 6 1 9 3 8 4 7 5]
 [3 9 2 4 5 8 1 7 6]
 [3 1 6 9 8 4 7 5 2]
 [1 4 3 9 6 7 8 2 5]
 [2 1 9 8 4 5 7 6 3]
 [1 4 3 9 7 8 2 6 5]
 [9 2 8 1 4 7 3 5 6]]


In [108]:
def esSolucion(sudoku):
    for i in range(9):
        print(sudoku[:,i])
        correct = correcto(sudoku[:,i])
        if not correct:
            return False

SyntaxError: invalid syntax (<ipython-input-28-6b639795863a>, line 3)

In [ ]:
def esSolucion(array):
    lv = []
    for i in sudoku:
        print(i)
        if correcto(i) == True:
            print('si')
            lv.append(descomponer3x3(i))
        else:
            print('no')
    print(lv)

In [ ]:
def check_sudoku(arreglo):
    
    for fila in arreglo:
        if sorted(list(set(fila))) != sorted(fila):
            return False
    # check the cols
    cols = []
    for columna in range(len(arreglo)):
        for columna in arreglo:
            cols = [fila[columna]]
        # set will get unique values, its converted to list so you can compare
        # it's sorted so the comparison is done correctly.
        if sorted(list(set(cols))) != sorted(cols):
            return False
        cols = []
    # if you get past all the false checks return True
    return True

In [ ]:
check_sudoku(sudoku)

In [ ]:
descomponer3x3(sudoku)

(c) Crea la función `esSolucion` que recibe un `array` de $9\times 9$ y devuelve si es o no solución del sudoku.

In [ ]:
v = []
    for i in array:
        if correcto(i) == True:
            sudoku3 = descomponer3x3(i)
            lv.append(sudoku3)
        else:
            print('Está incorrecto')
    print(lv)

In [ ]:
esSolucion(sudoku)