# **Ejercicios de NumPy**

In [1]:
%pylab inline
import numpy as np

Populating the interactive namespace from numpy and matplotlib


## Pregunta 1
Crea los siguientes arreglos con los tipos correctos.

Un arreglo de $5 \times 5$ cuya diagonal sean $[2.0, 3.0, 4.0, 5.0]$
Un arreglo de $4 \times 4$ cuyo último renglón sea $[1,2,3,4]$ y el resto sean $0$.

In [34]:
arr = np.array([1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,1.0,0.0,0.0,0.0,5.0]).reshape((5,5))
print('Diagonal: [1.0,2.0,3.0,4.0,5.0]  ')
print(arr)

Diagonal: [1.0,2.0,3.0,4.0,5.0]  
[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [1. 0. 0. 0. 5.]]


In [35]:
arr = np.array([0,0,0,0,0,0,0,0,0,0,0,0,1,2,3,4]).reshape((4,4))
print('Último renglón:   [1,2,3,4] ')
print(arr)

Último renglón:   [1,2,3,4] 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


# Pregunta 2
En este ejercicio realizaremos una criba de Eratóstenes

(a) Crea un arreglo de booleanos de shape (100,), con todos sus elementos True. El índice representa el número.

In [36]:
bool_arr = np.ones((100,), dtype=bool)


(b) "Tacha" los elementos 0 y 1.

(c) Para cada entero subsiguiente, tacha sus múltiplos. Una manera de hacerlo es el código que se muestra. Explica que hace el código, sobretodo explica que hace el slicing.

In [8]:
N_max = int(np.sqrt(len(bool_arr)))
for j in range(2, N_max):
    bool_arr[2*j::j] = False

In [9]:
bool_arr

array([ True,  True,  True,  True, False,  True, False,  True, False,
       False, False,  True, False,  True, False, False, False,  True,
       False,  True, False, False, False,  True, False, False, False,
       False, False,  True, False,  True, False, False, False, False,
       False,  True, False, False, False,  True, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False,  True, False,  True, False,
       False, False, False, False,  True, False, False, False,  True,
       False,  True, False, False, False, False, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False, False, False,  True, False,
       False])


(d) Mira la documentacion de np.nonzero para imprimir todos los números primos.

(e) Encapsula lo que acabamos de hacer en una función llamada criba_eratostenes, que reciba como argumento maximo el cual representa el tamaño del array. Muestra el resultado para maximo = {10, 100, 200}, usando un for.

# Pregunta 3
Crea un cubo rubik, partiendo de un arreglo de ceros y usando slicing dibuja cada una de las caras como si estuviera resuelto (cada color un entero a partir del $1$). Muestra con indexing que está resuelto (es decir, imprime las seis caras). ¿Cuántos elementos del arreglo quedaron en $0$?

In [74]:
arr = np.zeros(54)
arr.shape = (6,3,3)
for i in range(1,6):
    arr[i]=i

print('Los elementos que quedaron en 0 fueron solo los de 1 sala cara del cubo')
print(arr)


Los elementos que quedaron en 0 fueron solo los de 1 sala cara del cubo
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]]


# Pregunta 4
El Sudoku es un pasatiempo que consiste en un arreglo $9 \times 9$ de celdas, con dígitos del 1 al 9, de tal manera que no se repiten valores en cada columna, cada renglón y en cada subarreglo de $3\times 3$.

(a) Crea una función llamada correcto que reciba un array $1d$ de tamaño 9 e indique si está completo o no (i.e. incluye los números del 1 al 9.

(b) Crea una función llamada descomponer3x3 que reciba un array de enteros de $9\times 9$ y lo separe en sus 9 subarreglos $3\times3$.

(c) Crea la función esSolucion que recibe un array de $9\times 9$ y devuelve si es o no solución del sudoku.

In [94]:
#Se crea la función para verificar si el array de tamaño 9 está correcto
def correcto(arr):
    lista = [1,2,3,4,5,6,7,8,9]
    #Se verifica que sea del tamaño correcto
    if len(arr)!=9:
        return False
    #Se verifica que todos los números esten correctos
    for element in lista:
        if element not in arr:
            return False
    return True

#se verifica qeu funcione:
print('Verificación de que la función "correcto" funcione:')
arrCorr=np.arange(1,10)
arrM1=np.arange(0,10)
arrM2=np.arange(1,11)

print('Arreglo bueno: ',correcto(arrCorr))
print('Arreglo malo (tamaño incorrecto): ',correcto(arrM1))
print('Arreglo malo (números incorrectos): ',correcto(arrM2))


#Se crea la función descomponer3x3 que recibe una array de 9x9 y lo separa en subarreglos de 3x3
def descomponer3x3(arr):
    arr_slice1 = arr[0][0:3]
    arr_slice2 = arr[1][0:3]
    arr_slice3 = arr[2][0:3]
    arr1=np.array([arr_slice1,arr_slice2,arr_slice3]).reshape(3,3)
    
    arr_slice1 = arr[0][3:6]
    arr_slice2 = arr[1][3:6]
    arr_slice3 = arr[2][3:6]
    arr2=np.array([arr_slice1,arr_slice2,arr_slice3]).reshape(3,3)
    
    arr_slice1 = arr[0][6:9]
    arr_slice2 = arr[1][6:9]
    arr_slice3 = arr[2][6:9]
    arr3=np.array([arr_slice1,arr_slice2,arr_slice3]).reshape(3,3)
    
    arr_slice1 = arr[3][0:3]
    arr_slice2 = arr[4][0:3]
    arr_slice3 = arr[5][0:3]
    arr4=np.array([arr_slice1,arr_slice2,arr_slice3]).reshape(3,3)
    
    arr_slice1 = arr[3][3:6]
    arr_slice2 = arr[4][3:6]
    arr_slice3 = arr[5][3:6]
    arr5=np.array([arr_slice1,arr_slice2,arr_slice3]).reshape(3,3)
    
    arr_slice1 = arr[3][6:9]
    arr_slice2 = arr[4][6:9]
    arr_slice3 = arr[5][6:9]
    arr6=np.array([arr_slice1,arr_slice2,arr_slice3]).reshape(3,3)

    arr_slice1 = arr[6][0:3]
    arr_slice2 = arr[7][0:3]
    arr_slice3 = arr[8][0:3]
    arr7=np.array([arr_slice1,arr_slice2,arr_slice3]).reshape(3,3)
    
    arr_slice1 = arr[6][3:6]
    arr_slice2 = arr[7][3:6]
    arr_slice3 = arr[8][3:6]
    arr8=np.array([arr_slice1,arr_slice2,arr_slice3]).reshape(3,3)
    
    arr_slice1 = arr[6][6:9]
    arr_slice2 = arr[7][6:9]
    arr_slice3 = arr[8][6:9]    
    arr9=np.array([arr_slice1,arr_slice2,arr_slice3]).reshape(3,3)
    
    return arr1,arr2,arr3,arr4,arr5,arr6,arr7,arr8,arr9


#se verifica que la función descomponga el arreglo:
print('\n')
print('\nVerificación de que la función "descomponer3x3" funcione:')
arr = np.array([1,1,1,2,2,2,3,3,3,1,1,1,2,2,2,3,3,3,1,1,1,2,2,2,3,3,3,4,4,4,5,5,5,6,6,6,4,4,4,5,5,5,6,6,6,4,4,4,5,5,5,6,6,6,7,7,7,8,8,8,9,9,9,7,7,7,8,8,8,9,9,9,7,7,7,8,8,8,9,9,9]).reshape((9,9))
descomponer3x3(arr)

Verificación de que la función "correcto" funcione:
Arreglo bueno:  True
Arreglo malo (tamaño incorrecto):  False
Arreglo malo (números incorrectos):  False



Verificación de que la función "descomponer3x3" funcione:


(array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]),
 array([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]),
 array([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]),
 array([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]]),
 array([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]),
 array([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]]),
 array([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]),
 array([[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]]),
 array([[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]]))

# Pregunta 5
Utiliza el archivo sunspots.txt (localizado en la carpeta data), el cual contiene el número de manchas solares por cada mes desde enero de 1749. La primera columna es el mes, el segundo el número de manchas.

(a) Escribe el código que lea el archivo y haga una gráfica de las manchas en función del tiempo. Formatea el eje $x$ para que se muestren cada 25 años empezando en $1750$.# 

(b) Calcula el promedio móvil. Dibújalo sobre el dibujo original.    (gráfica en calidad de publicación)

# Pregunta 6
Utiliza el archivo starts.txt (localizado en la carpeta data), el cual contiene la temperatura y magnitud de varias estrellas en la Vía Lactea. Usa esta información para dibujar un scatter plot del logaritmo del brillo vs. la temperatura (en K). Este diagrama se conoce como diagrama de Hertzsprung-Russell.

(a) Lee el archivo y dibuja los datos tal como vienen en el archivo. Agrega etiquetas y formatea la gráfica de tal manera que tenga calidad de publicación.

(b) Ahora usa el xlim() y ylim() para que quede de manera correcta el diagrama. Hay regiones donde las estrellas parece que se aglomeran, ve el archivo de wikipedia y agrega anotaciones para explicarlas.