# **Ejercicios de NumPy**

In [1]:
%pylab inline
import numpy as np

Populating the interactive namespace from numpy and matplotlib


# Pregunta 1

Crea los siguientes arreglos con los tipos correctos.


* Un arreglo de $5 \times 5$ cuya diagonal sean $[1.0, 2.0, 3.0, 4.0, 5.0]$ 
* Un arreglo de $4 \times 4$ cuyo último renglón sea $[1,2,3,4]$ y el resto sean $0$.

# Pregunta 2

En este ejercicio realizaremos una criba de Eratóstenes
**Nota**: Ejercicio basado en el presentado en `C4P`.
(a) Crea un arreglo de booleanos de shape (100,), con todos sus elementos True. El índice representa el número.

In [2]:
bool_arr = np.ones((100,), dtype=bool)

(b) "Tacha" los elementos 0 y 1.

(c) Para cada entero subsiguiente, tacha sus múltiplos. Una manera de hacerlo es el código que se muestra. Explica que hace el código, sobretodo explica que hace el slicing.

In [ ]:
N_max = int(np.sqrt(len(bool_arr)))
for j in range(2, N_max):
    bool_arr[2*j::j] = False

In [ ]:
bool_arr

(d) Mira la documentacion de np.nonzero para imprimir todos los números primos.

(e) Encapsula lo que acabamos de hacer en una función llamada criba_eratostenes, que reciba como argumento maximo el cual representa el tamaño del array. Muestra el resultado para maximo = {10, 100, 200}, usando un for.

# Pregunta 3

Crea un cubo rubik, partiendo de un arreglo de ceros y usando slicing dibuja cada una de las caras como si estuviera resuelto (cada color un entero a partir del $1$). Muestra con indexing que está resuelto (es decir, imprime las seis caras). ¿Cuántos elementos del arreglo quedaron en $0$?

In [3]:
cubo=np.zeros((6,3,3)).astype(int)
for i in range (6):
    cubo[i]=1+i
print(cubo)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[4 4 4]
  [4 4 4]
  [4 4 4]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[6 6 6]
  [6 6 6]
  [6 6 6]]]


# Pregunta 4

El Sudoku es un pasatiempo que consiste en un arreglo $9 \times 9$ de celdas, con dígitos del 1 al 9, de tal manera que no se repiten valores en cada columna, cada renglón y en cada subarreglo de $3\times 3$.

(a) Crea una función llamada correcto que reciba un array $1d$ de tamaño 9 e indique si está completo o no (i.e. incluye los números del 1 al 9.

(b) Crea una función llamada descomponer3x3 que reciba un array de enteros de $9\times 9$ y lo separe en sus 9 subarreglos $3\times3$.

(c) Crea la función esSolucion que recibe un array de $9\times 9$ y devuelve si es o no solución del sudoku.



In [9]:
def correcto(array):
    if array.size != 9:
        raise Exception('Forma equivocada')
        
    if sorted(array) == [1,2,3,4,5,6,7,8,9]:
        return True
    return False

def descomponer3x3(array):
    if array.shape != (9,9):
        raise Exception('Forma equivocada')
        
    subarreglos = []
    for desc_vert in np.vsplit(array,3):
        for subarreglo in np.hsplit(desc_vert,3):
            subarreglos.append(subarreglo)
    return subarreglos

def esSolucion(array):
    if array.shape != (9,9):
        raise Exception('Forma equivocada')
    
    for row in array:
        if not correcto(row):
            return False

    for col in array.T:
        if not correcto(col):
            return False
    
    for subarreglo in descomponer3x3(array):
        if not correcto(subarreglo.reshape(9)):
            return False
    return True

In [10]:
# Función que construye una solución de Sudoku 

def construye_solucion(arr,row,col):
    if col == 9:
        col = 0
        row = row + 1
        if row == 9:
            return arr
    
    for posible_num in range(1,10):
        
        valid = True
        
        for num in arr[row,:]:
            if num == posible_num:
                valid = False
                
        for num in arr[:, col]:
            if num == posible_num:
                valid = False
                
        for num in descomponer3x3(arr)[int(row / 3)*3 + int(col / 3)].reshape(9):
            if num == posible_num:
                valid = False
                
        if valid:
            arr[row,col] = posible_num
            value = construye_solucion(arr, row, col+1)
            if value is not None:
                return value
            arr[row,col] = 0
            
solucion = construye_solucion(np.zeros((9,9)),0,0)
solucion

array([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [4., 5., 6., 7., 8., 9., 1., 2., 3.],
       [7., 8., 9., 1., 2., 3., 4., 5., 6.],
       [2., 1., 4., 3., 6., 5., 8., 9., 7.],
       [3., 6., 5., 8., 9., 7., 2., 1., 4.],
       [8., 9., 7., 2., 1., 4., 3., 6., 5.],
       [5., 3., 1., 6., 4., 2., 9., 7., 8.],
       [6., 4., 2., 9., 7., 8., 5., 3., 1.],
       [9., 7., 8., 5., 3., 1., 6., 4., 2.]])

In [11]:
esSolucion(solucion)

True

In [170]:
#Este es un ejemplo de una solución que es falsa, se cambio el último número 
#de la que está arriba, podemos darnos cuenta que por eso sale false
le puedes mover algunos por ahí para ver que la función esSolucion te dice false

mala = np.array([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
                   [4., 5., 6., 7., 8., 9., 1., 2., 3.],
                   [7., 8., 9., 1., 2., 3., 4., 5., 6.],
                   [2., 1., 4., 3., 6., 5., 8., 9., 7.],
                   [3., 6., 5., 8., 9., 7., 2., 1., 4.],
                   [8., 9., 7., 2., 1., 4., 3., 6., 5.],
                   [5., 3., 1., 6., 4., 2., 9., 7., 8.],
                   [6., 4., 2., 9., 7., 8., 5., 3., 1.],
                   [9., 7., 8., 5., 3., 1, 6., 4., 1.]]) #El último era 2 y lo cambie por 1

esSolucion(mala)

False

# Pregunta 5

Utiliza el archivo sunspots.txt (localizado en la carpeta data), el cual contiene el número de manchas solares por cada mes desde enero de 1749. La primera columna es el mes, el segundo el número de manchas.

(a) Escribe el código que lea el archivo y haga una gráfica de las manchas en función del tiempo. Formatea el eje $x$ para que se muestren cada 25 años empezando en $1750$.

**NOTA:** La gráfica debe de estar en calidad de publicación

(b) Calcula el promedio móvil. Dibújalo sobre el dibujo original.

# Pregunta 6

Utiliza el archivo starts.txt (localizado en la carpeta data), el cual contiene la temperatura y magnitud de varias estrellas en la Vía Lactea. Usa esta información para dibujar un scatter plot del logaritmo del brillo vs. la temperatura (en K). Este diagrama se conoce como diagrama de Hertzsprung-Russell.

(a) Lee el archivo y dibuja los datos tal como vienen en el archivo. Agrega etiquetas y formatea la gráfica de tal manera que tenga calidad de publicación.

(b) Ahora usa el xlim() y ylim() para que quede de manera correcta el diagrama. Hay regiones donde las estrellas parece que se aglomeran, ve el archivo de wikipedia y agrega anotaciones para explicarlas.