Resuelva usando regla de Cramer

$3x + 6y -5z = 12$

$x - 3y + 2z = -2$

$5x -y + 4z = 10$



In [55]:
%pylab inline
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg # Biblioteca para algebra lineal

Populating the interactive namespace from numpy and matplotlib


In [71]:
A = np.matrix([[3,6,-5],
              [1,-3,2],
              [5,-1,4]])
A


matrix([[ 3,  6, -5],
        [ 1, -3,  2],
        [ 5, -1,  4]])

In [57]:
B = np.matrix([[12],
               [-2],
               [10]])
B

matrix([[12],
        [-2],
        [10]])

In [78]:
Ax = np.matrix(A)
Ax[:,0]=B
Ax


matrix([[12,  6, -5],
        [-2, -3,  2],
        [10, -1,  4]])

In [59]:
Ay = np.matrix(A)
Ay[:,1]=B
Ay

matrix([[ 3, 12, -5],
        [ 1, -2,  2],
        [ 5, 10,  4]])

In [60]:
Az = np.matrix(A)
Az[:,2]=B
Az

matrix([[ 3,  6, 12],
        [ 1, -3, -2],
        [ 5, -1, 10]])

In [69]:
print(det(Ax))
print(det(Ay))
print(det(Az))
print("x = ",det(Ax)/det(A))
print("y = ",det(Ay)/det(A))
print("z = ",det(Az)/det(A))

-111.99999999999996
-111.99999999999996
-47.999999999999986
x =  1.75
y =  1.75
z =  0.75


In [68]:
Xs = [det(Ax)/det(A), det(Ay)/det(A), det(Az)/det(A)]
Xs

[1.75, 1.75, 0.75]