In [2]:
import numpy as np

In [3]:
np.random.rand(3)

array([0.27993773, 0.06063831, 0.39583825])

In [4]:
np.random.rand(3)*100

array([93.03124182, 70.31111978, 14.94189579])

In [7]:
np.random.seed(9)
np.random.rand(9)

array([0.01037415, 0.50187459, 0.49577329, 0.13382953, 0.14211109,
       0.21855868, 0.41850818, 0.24810117, 0.08405965])

In [ ]:
arr = np.arange(10)

In [ ]:
arr_slice =  arr[5:8] #Comparten memoria, modificas uno, modificas el otro.

In [ ]:
np.sign(arr) #te dice el signo 1 positivo, -1 negativo, 0 el 0