# Ejercicios de NumPy

In [156]:
%pylab inline
import numpy as np
import matplotlib.pyplot as plt

#Ejercicio 1
arr5x5 = np.ones((5,5))
for i in range(5):
    arr5x5[i]=i+1
arr4x4 = np.zeros((4,4))
arr4x4[3] = np.arange(1,5)
print("Ejercicio 1:")
print(arr5x5)#Arreglo de 5x5
print(arr4x4)#Arreglo de 4x4

#Ejercicio 2
def criba_eratostenes(maximo):
    bool_arr = np.ones((maximo), dtype=bool)
    bool_arr[:2] = False
    N_max = int(np.sqrt(len(bool_arr)))
    print(N_max)
    for j in range(2, N_max+1):#Agregue N_max+1 por que N_max no tomaba los multiplos de 3 cuando maximo=10, entonces estaba mostrando a 9 como primo
        bool_arr[2*j::j] = False # El slicing lo que indica es que del elemnto en el lugar 2*j al último sea false cada j elementos. 
                                #Si tomamos el primer j que es dos sería: [4::2]=false, lo que signigica que de la posición 4 hasta 
                                #la ultima posicion va a poner un false cada 2 elementos.
    primos = np.nonzero(bool_arr) #La función nonzero regresa los indices de los elementos que no son cero. De modo que cada indice
    return primos
maximo = {10,100,200}
for i in maximo:
    print("Los primos del 1 al "+str(i)+" son: \n"+str(criba_eratostenes(i))+"")#Aqui muestro cada resultado de criba con cada elemento de maximo

#Ejercicio 3
#verde=1,blanco=2,rojo=3,naranja=4,azul=5,amarillo=6
cubo = np.zeros((6,3,3))
for i in range(len(cubo)):
    cubo[i]=i+1
cubo[[0,1,2,3,4,5]]#ningún elemento del arreglo queda en 0 ya que, cada color tiene -
#asignado un número a partir del 1. De modo que cuando el cubo está resuelto, cada cara -
#tiene un único color.


#Ejercicio 4
#En la funcion correcto tomo un arreglo de 9 elementos o una matriz de 3x3
#dentro del while itero del 1 al 9, para ver si están todos los números dentro
#de la matriz o de la linea. Esto verifica que no se repitan por cuadro,fila,columna
def correcto(linea):
    res = True
    i = 1
    while res and i <= 9:
        if i in linea:
            i += 1
        else:
            res = False
    return res
linea = np.arange(1,10)
#En esta funcion recorro todo el arreglo de 9x9 con i como las filas y j las columnas
#lo que hice fue usar el slicing para agarrar cuadros de 3x3 con los i, j iterando
#cada dos lugares de modo que asi pudiera tomar 9 cuadros de 3x3 y meterlos en nuevoArr
#lo que me indica la matriz del nuevoArr es la banderaNa que se mueve cada que meto un nuevo cuadro
#de modo que el arreglo de 9x9 lo vi algo así:
#123 
#456
#789
#siendo cada entrada de una matriz de 3x3.
#y el nuevoArr asi:
#[1,2,3,4,5,6,7,8,9]
def descomponer(arr9x9):
    nuevoarr = np.ones((9,3,3))
    banderaNA = 0
    for i in range(2,len(arr9x9),3):
        for j in range(2,len(arr9x9),3):
            nuevoarr[banderaNA] = arr9x9[i-2:i+1,j-2:j+1]
            banderaNA += 1
    return nuevoarr
#Al final solamente junte todo en esSolucion. Recibo el arreglo 9x9 y lo transforme.
#Despues tomo ese nuevoArr y el arr9x9 y les aplico la funcion de correcto.
#bandera1 indica si es correcto cada matriz de 3x3,bandera2 indica si cada 
#fila del arreglo9x9 está bien y la bandera3 toma las columas con el arreglo9x9 transpuesto.
def esSolucion(arr9x9):
    nuevoArr = descomponer(arr9x9)
    sol = True
    for i in range(len(arr9x9)):
        bandera1 = correcto(nuevoArr[i])
        bandera2 = correcto(arr9x9[i])
        bandera3 = correcto(arr9x9.T[i])
        if bandera1 and bandera2 and bandera3 == False:
            sol = False
            break
    return sol            
sudokuBueno = np.array([[7 ,9 ,2 ,6 ,1 ,5 ,3 ,8 ,4 ],
[5 ,8 ,3 ,7 ,4 ,2 ,6 ,9 ,1 ],
[1 ,6 ,4 ,3 ,9 ,8 ,5 ,2 ,7 ],
[9 ,4 ,8 ,2 ,6 ,3 ,7 ,1 ,5 ],
[2 ,7 ,5 ,4 ,8 ,1 ,9 ,6 ,3 ],
[6 ,3 ,1 ,9 ,5 ,7 ,2 ,4 ,8 ],
[8 ,5 ,7 ,1 ,2 ,9 ,4 ,3 ,6 ],
[3 ,2 ,6 ,8 ,7 ,4 ,1 ,5 ,9 ],
[4 ,1 ,9 ,5 ,3 ,6 ,8 ,7 ,2]])
sudokuMalo = np.array([[7 ,7 ,2 ,6 ,1 ,5 ,3 ,8 ,4 ],
[5 ,8 ,3 ,7 ,4 ,2 ,6 ,9 ,1 ],
[1 ,6 ,4 ,3 ,9 ,8 ,5 ,2 ,7 ],
[9 ,4 ,8 ,2 ,6 ,3 ,7 ,1 ,5 ],
[2 ,7 ,5 ,4 ,8 ,1 ,9 ,6 ,3 ],
[6 ,3 ,1 ,9 ,5 ,7 ,2 ,4 ,8 ],
[8 ,5 ,7 ,1 ,2 ,9 ,4 ,3 ,6 ],
[3 ,2 ,6 ,8 ,7 ,4 ,1 ,5 ,9 ],
[4 ,1 ,9 ,5 ,3 ,6 ,8 ,7 ,2]])

print(esSolucion(sudokuBueno))
print(esSolucion(sudokuMalo))

#Ejercicio 5


archivo = open('/home/jovyan/Matematicas-computacionales-fall2020/week3/data/sunspots.txt')
x = np.array([])
y = np.array([])
y2 = np.array([])
#En este for meti la info del archivo en dos arrays: x para los meses,y para las manchas.
for line in archivo:
    fecha = 1750 + (int(line.split()[0]))/12
    x = np.append(x,fecha)
    y = np.append(y,float(line.split()[1]))
#Con este trate de hacer el movin average pero no me salio gráficarlo
for i in range(300,len(y),300):
    y2 = np.append(y2,y[i-300:i].sum())
y2 = np.append(y2,y[3000:len(y)].sum())
y2 = y2/300
plt.figure(figsize=(10, 6), dpi=80)
plt.plot(x,y, color="red", linewidth=1)
#plt.plot(y2, color="blue", linewidth=1)
plt.xlim(x[0],x[len(x)-1],25)



Populating the interactive namespace from numpy and matplotlib
Ejercicio 1:
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 2. 3. 4.]]
14
Los primos del 1 al 200 son: 
(array([  2,   3,   5,   7,  11,  13,  17,  19,  23,  29,  31,  37,  41,
        43,  47,  53,  59,  61,  67,  71,  73,  79,  83,  89,  97, 101,
       103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167,
       173, 179, 181, 191, 193, 197, 199]),)
3
Los primos del 1 al 10 son: 
(array([2, 3, 5, 7]),)
10
Los primos del 1 al 100 son: 
(array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97]),)
True
False
