# Introducción

**NumPy** es la *librería* de python para computación científica. **NumPy** agrega al lenguaje lo siguiente: Arreglos multidimensionales, operaciones elemento por elemento (técnica conocida como *broadcasting*), algebra lineal, manipulación de imágenes, la habilidad de utilizar código `C/C++` y `FORTRAN`, entre muchas otras.

La mayor parte de los componentes del sistema de computo científico de Python, están construidas encima de **NumPy**, un ejemplo que veremos en el curso es `SciPy`.

Para poder utilizar **NumPy**, es necesario importarlo a la sesión del `notebook`.

### Bibliografía de soporte

- *NumPy Beginner's Guide* _Ivan Idris_,  PACKT Publishing, 2012
- *NumPy Cookbook* _Ivan Idris_, PACKT Publishing, 2012
- *Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython*, _Wes McKinney_, O'REILLY, 2012

In [1]:
import numpy as np

## Arrays

El principal componente de **NumPy** es el `array`, el cual es una versión más poderosa, pero menos flexible que las listas de python.

In [2]:
lst =  [1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
lst[1:3]

[2, 3]

In [5]:
arr[1:3]

array([2, 3])

<div class="alert alert-info">
**Ejercicio:** Repite los ejercicios de listas del *Lecture 2* con `array`.
</div>

In [6]:
lst[-1] = "Las listas pueden tener varios tipos de datos"
lst

[1, 2, 3, 4, 'Las listas pueden tener varios tipos de datos']

In [7]:
arr[-1] = "Los arreglos no..."
#No se pueden poner varios tipos de datos

ValueError: invalid literal for int() with base 10: 'Los arreglos no...'

Una vez inicializado el `array` sólo puede contener un tipo de dato.

In [8]:
arr.dtype
#Es un entero de 64 bytes

dtype('int64')

In [9]:
arr[-1] = 1.23456
arr

array([1, 2, 3, 4, 1])

In [10]:
arr.dtype

dtype('int64')

Sacrificamos la versatilidad de las listas por velocidad. Creeemos un `array` de 1 millón de elementos y multiplicaremos cada uno de ellos por una constante (*broadcasting*). --> hacerle operaciones a todos los elementos

In [13]:
arr = np.arange(1e7)  
arr

array([0.000000e+00, 1.000000e+00, 2.000000e+00, ..., 9.999997e+06,
       9.999998e+06, 9.999999e+06])

In [15]:
#Convierte un arreglo a lista
lst = arr.tolist()
lst

[0.0,
 1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 9.0,
 10.0,
 11.0,
 12.0,
 13.0,
 14.0,
 15.0,
 16.0,
 17.0,
 18.0,
 19.0,
 20.0,
 21.0,
 22.0,
 23.0,
 24.0,
 25.0,
 26.0,
 27.0,
 28.0,
 29.0,
 30.0,
 31.0,
 32.0,
 33.0,
 34.0,
 35.0,
 36.0,
 37.0,
 38.0,
 39.0,
 40.0,
 41.0,
 42.0,
 43.0,
 44.0,
 45.0,
 46.0,
 47.0,
 48.0,
 49.0,
 50.0,
 51.0,
 52.0,
 53.0,
 54.0,
 55.0,
 56.0,
 57.0,
 58.0,
 59.0,
 60.0,
 61.0,
 62.0,
 63.0,
 64.0,
 65.0,
 66.0,
 67.0,
 68.0,
 69.0,
 70.0,
 71.0,
 72.0,
 73.0,
 74.0,
 75.0,
 76.0,
 77.0,
 78.0,
 79.0,
 80.0,
 81.0,
 82.0,
 83.0,
 84.0,
 85.0,
 86.0,
 87.0,
 88.0,
 89.0,
 90.0,
 91.0,
 92.0,
 93.0,
 94.0,
 95.0,
 96.0,
 97.0,
 98.0,
 99.0,
 100.0,
 101.0,
 102.0,
 103.0,
 104.0,
 105.0,
 106.0,
 107.0,
 108.0,
 109.0,
 110.0,
 111.0,
 112.0,
 113.0,
 114.0,
 115.0,
 116.0,
 117.0,
 118.0,
 119.0,
 120.0,
 121.0,
 122.0,
 123.0,
 124.0,
 125.0,
 126.0,
 127.0,
 128.0,
 129.0,
 130.0,
 131.0,
 132.0,
 133.0,
 134.0,
 135.0,
 136.0,
 137.0,
 138.0

Las listas no soportan **broadcasting** por lo que crearemos una función que lo simule

In [16]:
def lst_multiplicacion( alist , scalar ): 
    for i , val in enumerate ( alist ): 
        alist [ i ] = val
    return alist

In [17]:
%timeit arr * 1.1

19.3 ms ± 2.72 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [18]:
%timeit lst_multiplicacion(lst, 1.1)

1.38 s ± 257 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Creación de arrays

In [19]:
arr = np.array([1,2,3,4,5]) #Convierte lista en arreglo

In [20]:
arr

array([1, 2, 3, 4, 5])

In [21]:
arr = np.arange(10,21) #Convierte range en arregle

In [22]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
arr = np.zeros(5) #Crea array de 0

In [24]:
arr

array([0., 0., 0., 0., 0.])

In [25]:
arr = np.linspace(0,1,100) #Cota inferior, cota superior, cantidad partes

In [26]:
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [27]:
arr = np.logspace(0,1,100, base=10) 
#Genera del 0 a 1 (donde log da 0 y donde 1) en escala logaritmica con 100 cortes y en esa base
#Sirve para distribuir mejor los datos (mas lentamente)

In [28]:
arr

array([ 1.        ,  1.02353102,  1.04761575,  1.07226722,  1.09749877,
        1.12332403,  1.149757  ,  1.17681195,  1.20450354,  1.23284674,
        1.26185688,  1.29154967,  1.32194115,  1.35304777,  1.38488637,
        1.41747416,  1.45082878,  1.48496826,  1.51991108,  1.55567614,
        1.59228279,  1.62975083,  1.66810054,  1.70735265,  1.7475284 ,
        1.78864953,  1.83073828,  1.87381742,  1.91791026,  1.96304065,
        2.009233  ,  2.05651231,  2.10490414,  2.15443469,  2.20513074,
        2.25701972,  2.3101297 ,  2.36448941,  2.42012826,  2.47707636,
        2.53536449,  2.59502421,  2.65608778,  2.71858824,  2.7825594 ,
        2.84803587,  2.91505306,  2.98364724,  3.05385551,  3.12571585,
        3.19926714,  3.27454916,  3.35160265,  3.43046929,  3.51119173,
        3.59381366,  3.67837977,  3.76493581,  3.85352859,  3.94420606,
        4.03701726,  4.1320124 ,  4.22924287,  4.32876128,  4.43062146,
        4.53487851,  4.64158883,  4.75081016,  4.86260158,  4.97

In [29]:
arr2d = np.zeros((5,5)) #(5x5)

In [30]:
arr2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
cubo = np.zeros((5,5,5)).astype(int)+1 #Le sumo uno a todo

In [32]:
cubo

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [33]:
cubo = np.ones((5,5,5)).astype(np.float16)

In [34]:
cubo

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float16)

In [35]:
cubo.dtype

dtype('float16')

In [36]:
np.empty((2,3,4)) #Revuelve arreglo con basura

array([[[4.66069997e-310, 0.00000000e+000, 4.66069924e-310,
         4.66069924e-310],
        [4.66069924e-310, 4.66069924e-310, 4.66069924e-310,
         4.66069924e-310],
        [4.66069924e-310, 4.66069924e-310, 4.66069924e-310,
         4.66069924e-310]],

       [[4.66069924e-310, 4.66069924e-310, 4.66069924e-310,
         4.66069924e-310],
        [4.66069924e-310, 4.66069924e-310, 4.66069924e-310,
         4.66069924e-310],
        [4.66069924e-310, 4.66069924e-310, 4.66069924e-310,
         4.66069924e-310]]])

<div class="alert alert-danger">
**PELIGRO**

¡`np.empty` no devuelve un arreglo de ceros!
</div>

In [38]:
np.eye(4) #Pone 1 en la diagonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
np.random.seed(10) #Especifica la semilla para sacar el random (Ya no es tan random)
np.random.rand(10)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

## Reshaping

In [41]:
arr = np.arange(1000)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [42]:
arr3d = arr.reshape((10,10,10))
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [43]:
arr3d.ndim

3

In [44]:
arr3d.shape

(10, 10, 10)

In [45]:
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [46]:
arr = np.arange(200)

In [47]:
arr2d = arr.reshape((10,20))

In [48]:
arr2d

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
         33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 1

## Aplanar

In [49]:
arr = np.zeros((4,4,4,4))

In [50]:
arr.shape

(4, 4, 4, 4)

In [51]:
arr_plano = arr.ravel() #Lo hace de una sola dimension

In [52]:
arr_plano.shape

(256,)

In [53]:
arr_plano

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

## *Broadcasting*
Hace operaciones a todos los datos

In [54]:
data = np.array([1,2,3,4,5])

In [55]:
data

array([1, 2, 3, 4, 5])

In [56]:
data + 1

array([2, 3, 4, 5, 6])

In [57]:
data * 2

array([ 2,  4,  6,  8, 10])

In [58]:
data ** 2

array([ 1,  4,  9, 16, 25])

## Transponer

In [59]:
arr = np.arange(15).reshape((3,5))

In [60]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

¿Qué pasa en varias dimensiones?

In [62]:
arr  = np.arange(16).reshape((2,2,4))

In [63]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [64]:
arr.transpose((1,0,2)) #Para decidir como permutarlos

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

`transpose` recibe una `tupla` de los índices de los ejes y los permuta. `(O_o)`

<div class="alert alert-info">
**Ejercicio** Diseña un ejemplo multidimensional, donde sea obvia la permutación
</div>

## Slicing e Indexado

En el ejercicio vimos que el indexado en `arrays` de 1D es igual que el indexado y *slicing* de las listas de python. ¿Pero que sucede en $n-$dimensiones?

### Cuidado al hacer *slicing*

In [65]:
arr = np.arange(10)

In [66]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

El _slincing_ genera (devuelve) una **vista**, si modificas el =array= original, la **vista** se ve modificada también.

In [67]:
arr_slice =  arr[5:8] 
#Es una vista del objeto, si modificas la vista se modifica el original

In [68]:
arr_slice

array([5, 6, 7])

In [69]:
arr_slice[1]= 12345678

In [70]:
arr_slice

array([       5, 12345678,        7])

In [71]:
arr

array([       0,        1,        2,        3,        4,        5,
       12345678,        7,        8,        9])

In [72]:
arr_slice[:] = 345

In [73]:
arr_slice

array([345, 345, 345])

In [74]:
arr

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [75]:
arr2 = np.copy(arr) #Crea una copia en la que no comparte memoria

In [76]:
arr2

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [77]:
arr2[5:8] = [5,6,7]

In [78]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [80]:
np.may_share_memory(arr, arr_slice) #Para saber si comparten memoria

True

In [81]:
np.may_share_memory(arr, arr2)

False

### Multidimensional

In [82]:
arr = np.arange(9)

In [83]:
arr.shape = (3,3) #Es como un reshape

In [84]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
arr.ndim

2

In [86]:
arr[2]

array([6, 7, 8])

In [87]:
arr[-1] #ultimo renglon

array([6, 7, 8])

In [88]:
arr[1][1] #El uno del renglon 1

4

In [89]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [90]:
arr[:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [91]:
arr[:1,:2]

array([[0, 1]])

In [92]:
arr[1:,:2]

array([[3, 4],
       [6, 7]])

In [93]:
arr[1,] #Nos da todas las columnas del primer renglon

array([3, 4, 5])

In [94]:
arr[1,:2]

array([3, 4])

In [95]:
arr[1,2:]

array([5])

In [96]:
arr[:,1:] #todos los renglones desde el primero

array([[1, 2],
       [4, 5],
       [7, 8]])

In [97]:
arr[:,:1] #Todos los renglones hasta la 1 columna -1

array([[0],
       [3],
       [6]])

<div class="alert alert-info">
**Ejercicio**:

Explique como funciona el *slicing* $n$-dimensional.
</div>

In [98]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [99]:
index = arr > 2 #arreglo booleanos

In [100]:
index

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [101]:
arr[index] #devuelve el arreglo dependiendo del booleano

array([3, 4, 5, 6, 7, 8])

In [102]:
arr2 = arr[index]

In [103]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [104]:
arr2

array([3, 4, 5, 6, 7, 8])

<div class="alert alert-info">
**Ejercicio:**
(a) Cree un arreglo de 2D $5\times5$ lleno de unos. (b) Utilice *slicing* para seleccionar 1 cuadrado alrededor del centro  y llénelo con $2$s.  (c) Utilice *slicing* para seleccionar  el centro y asígnele $4$. (d) Copie el arreglo. (e) Utilice *slicing* lógico para seleccionar el cuadro interno y asígnele cero. (f) En el cuadro copiado, al centro y al cuadro exterior asígnele $0$.
</div>

## Fancy Indexing

In [105]:
arr = np.ones((5,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [106]:
for i in range(5):
    arr[i] = i

In [107]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [108]:
arr[[4,3,1,2]] #le indico que renglon quiero y en que orden

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.]])

In [109]:
arr[[-3,-2,-1]] #El - indica ultimo --> y esto es una nueva matriz (vista)

array([[2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

¿Puedes explicar que hace el _fancy indexing_?

## Funciones Universales

Las *funciones universales*  realizan operaciones elemento por elemento en los arreglos. 

In [110]:
arr = np.arange(10)

In [111]:
arr = -1*arr #Es un broadcasting

In [112]:
arr

array([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [114]:
#Es el infinito
np.Inf

inf

In [115]:
arr = np.abs(arr)

In [116]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [119]:
#Devuelve el signo del arreglo
np.sign(arr)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [120]:
np.isfinite(arr) #Saber si es finito

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [121]:
np.logical_not(arr) #Solo en 0 da True

array([ True, False, False, False, False, False, False, False, False,
       False])

In [122]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
arr = np.random.randn(10)
#Genera 10 numeros aleatorios

In [126]:
arr

array([-1.13660221,  0.13513688,  1.484537  , -1.07980489, -1.97772828,
       -1.7433723 ,  0.26607016,  2.38496733,  1.12369125,  1.67262221])

In [128]:
np.ceil(arr)
#Techo

array([-1.,  1.,  2., -1., -1., -1.,  1.,  3.,  2.,  2.])

In [130]:
np.floor(arr)
#Piso

array([-2.,  0.,  1., -2., -2., -2.,  0.,  2.,  1.,  1.])

In [131]:
np.rint(arr) #Lo redondea

array([-1.,  0.,  1., -1., -2., -2.,  0.,  2.,  1.,  2.])

In [132]:
arr2 = np.ones(10)

In [133]:
np.add(arr, arr2) #Suma los 2 arreglos

array([-0.13660221,  1.13513688,  2.484537  , -0.07980489, -0.97772828,
       -0.7433723 ,  1.26607016,  3.38496733,  2.12369125,  2.67262221])

In [134]:
np.multiply(arr, arr2)

array([-1.13660221,  0.13513688,  1.484537  , -1.07980489, -1.97772828,
       -1.7433723 ,  0.26607016,  2.38496733,  1.12369125,  1.67262221])

In [135]:
np.maximum(arr, arr2)

array([1.        , 1.        , 1.484537  , 1.        , 1.        ,
       1.        , 1.        , 2.38496733, 1.12369125, 1.67262221])

In [136]:
np.logical_and(arr, arr2)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## Agregaciones

Funciones que calculan operaciones a lo largo de un eje.

In [137]:
arr

array([-1.13660221,  0.13513688,  1.484537  , -1.07980489, -1.97772828,
       -1.7433723 ,  0.26607016,  2.38496733,  1.12369125,  1.67262221])

In [138]:
arr.sum()

1.1295171675409819

In [139]:
arr.mean()

0.11295171675409818

In [140]:
arr = np.random.randn(5,4)

In [141]:
arr

array([[ 0.09914922,  1.39799638, -0.27124799,  0.61320418],
       [-0.26731719, -0.54930901,  0.1327083 , -0.47614201],
       [ 1.30847308,  0.19501328,  0.40020999, -0.33763234],
       [ 1.25647226, -0.7319695 ,  0.66023155, -0.35087189],
       [-0.93943336, -0.48933722, -0.80459114, -0.21269764]])

In [142]:
arr.sum() #Suma todo el arreglo

0.6329089430523522

In [143]:
arr.mean()

0.03164544715261761

In [144]:
arr.sum(0) #Lo hace sobre las columnas

array([ 1.45734401, -0.17760608,  0.11731071, -0.7641397 ])

In [145]:
arr = np.arange(10)

In [146]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [147]:
arr.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [148]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [149]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [150]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [151]:
(arr > 5).sum()

4

## Operaciones de conjuntos

In [152]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [154]:
np.unique(arr2)

array([1.])

In [155]:
np.intersect1d(arr, arr2)

array([1.])

<div class="alert alert-info">
**Ejercicio** Usando la definición de [**cuadrados mágicos**](http://en.wikipedia.org/wiki/Magic_square) crea una función que reciba un arreglo e indique si es o no un cuadrado mágico.
</div>

## Casting

In [156]:
a = np.array([1,2,3])
a

array([1, 2, 3])

El tipo de mayor jerarquía define el _cast_

In [157]:
a + 1.5 
#Castea todo a reales (Gana la mayor jerarquia)

array([2.5, 3.5, 4.5])

La asignación **no** cambia el tipo del arreglo.

In [158]:
a.dtype

dtype('int64')

In [159]:
(a + 1.5).dtype

dtype('float64')

## Tipos 

In [165]:
np.iinfo(np.int64).max, 2**31 - 1   # Prueba con 8, 16, 32 y 64 bits
#Indica hasta que numero puede representar

(9223372036854775807, 2147483647)

<div class="alert alert-info">
**Ejercicio** ¿Qué pasa con `int`?
</div>

In [166]:
np.finfo(np.float64).max 

1.7976931348623157e+308

In [167]:
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [168]:
np.finfo(np.float32).eps #Abajo de ese valor se considera un cero

1.1920929e-07

In [169]:
np.float32(1e-8) + np.float32(1) == 1

True

In [170]:
np.float64(1e-8) + np.float64(1) == 1

False

## Estructura de datos

In [171]:
muestra = np.zeros((6,), dtype=[('codigo', 'S4'),('posicion', float), ('valor', float)]) #Indicas el nombre y tipo de dato
#Le pone un tipo de dato a cada dimension

In [172]:
muestra

array([(b'', 0., 0.), (b'', 0., 0.), (b'', 0., 0.), (b'', 0., 0.),
       (b'', 0., 0.), (b'', 0., 0.)],
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

In [173]:
muestra.ndim

1

In [174]:
muestra.shape

(6,)

In [175]:
muestra.dtype.names

('codigo', 'posicion', 'valor')

In [176]:
muestra[:] = [('ALFA',   1, 0.37), ('BETA', 1, 0.11), ('TAU', 1,   0.13),('ALFA', 1.5, 0.37), ('ALFA', 3, 0.11), ('TAU', 1.2, 0.13)]

In [177]:
muestra

array([(b'ALFA', 1. , 0.37), (b'BETA', 1. , 0.11), (b'TAU', 1. , 0.13),
       (b'ALFA', 1.5, 0.37), (b'ALFA', 3. , 0.11), (b'TAU', 1.2, 0.13)],
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

In [178]:
muestra.shape

(6,)

In [179]:
muestra['codigo']

array([b'ALFA', b'BETA', b'TAU', b'ALFA', b'ALFA', b'TAU'], dtype='|S4')

In [180]:
muestra[0]['valor']

0.37

In [181]:
muestra[['codigo', 'valor']]

array([(b'ALFA', 0.37), (b'BETA', 0.11), (b'TAU', 0.13), (b'ALFA', 0.37),
       (b'ALFA', 0.11), (b'TAU', 0.13)],
      dtype={'names':['codigo','valor'], 'formats':['S4','<f8'], 'offsets':[0,12], 'itemsize':20})

In [182]:
muestra[muestra['codigo'] == 'ALFA']

array([], shape=(0, 6),
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])