# Ejercicios de NumPy

In [2]:
%pylab inline
import numpy as np
import matplotlib.pyplot as plt

Populating the interactive namespace from numpy and matplotlib


## Pregunta 1
Crea los siguientes arreglos con los tipos correctos.

Un arreglo de $5 \times 5$ cuya diagonal sean $[1.0, 2.0, 3.0, 4.0, 5.0]$
Un arreglo de $4 \times 4$ cuyo último renglón sea $[1,2,3,4]$ y el resto sean $0$.

In [3]:
arr = np.eye(5)

for i in range(0,5):
    arr[i][i] += i
    
arr

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

In [4]:
arr2 = np.zeros((4,4))
arr2[3] = np.arange(4)+1
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 2., 3., 4.]])

# Pregunta 2
En este ejercicio realizaremos una criba de Eratóstenes

(a) Crea un arreglo de booleanos de shape (100,), con todos sus elementos True. El índice representa el número.

In [6]:
bool_arr = np.ones((100,), dtype=bool)

(b) "Tacha" los elementos 0 y 1.

In [7]:
bool_arr[0] = False
bool_arr[1] = False

(c) Para cada entero subsiguiente, tacha sus múltiplos. Una manera de hacerlo es el código que se muestra. Explica que hace el código, sobretodo explica que hace el slicing.



In [8]:
# Para la criba, solo debemos descartar los factores de los números tales que n < p^2.
N_max = int(np.sqrt(len(bool_arr)))
for j in range(2, N_max):
    bool_arr[2*j::j] = False # Toma una vista del arreglo de los elementos en las posiciones múltiplos de j
# Inicia en 2*j, suma j iterativamente y termina hasta el último elemento

bool_arr

array([False, False,  True,  True, False,  True, False,  True, False,
       False, False,  True, False,  True, False, False, False,  True,
       False,  True, False, False, False,  True, False, False, False,
       False, False,  True, False,  True, False, False, False, False,
       False,  True, False, False, False,  True, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False,  True, False,  True, False,
       False, False, False, False,  True, False, False, False,  True,
       False,  True, False, False, False, False, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False, False, False,  True, False,
       False])

(d) Mira la documentacion de np.nonzero para imprimir todos los números primos.

In [11]:
# np.nonzero?
np.nonzero(bool_arr)

(array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
        61, 67, 71, 73, 79, 83, 89, 97]),)

(e) Encapsula lo que acabamos de hacer en una función llamada criba_eratostenes, que reciba como argumento maximo el cual representa el tamaño del array. Muestra el resultado para maximo = {10, 100, 200}, usando un for.

In [12]:
def criba_eratostenes(maximo):
    bool_arr = np.ones((maximo,), dtype=bool)
    bool_arr[0] = False 
    bool_arr[1] = False 
    N_max = int(np.sqrt(len(bool_arr)))
    for j in range(2, N_max + 1):
        bool_arr[j*j::j] = False # Cambié el 2*j a j*j puesto que todos los múltiplos anteriores ya habrían sido verificados
    
    return np.nonzero(bool_arr)

In [16]:
m = [10,100,200]

for i in m:
    print("Primos menores o iguales que " + str(i))
    print(criba_eratostenes(i))

Primos menores o iguales que 10
(array([2, 3, 5, 7]),)
Primos menores o iguales que 100
(array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97]),)
Primos menores o iguales que 200
(array([  2,   3,   5,   7,  11,  13,  17,  19,  23,  29,  31,  37,  41,
        43,  47,  53,  59,  61,  67,  71,  73,  79,  83,  89,  97, 101,
       103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167,
       173, 179, 181, 191, 193, 197, 199]),)


## Pregunta 3
Crea un cubo rubik, partiendo de un arreglo de ceros y usando slicing dibuja cada una de las caras como si estuviera resuelto (cada color un entero a partir del $1$). Muestra con indexing que está resuelto (es decir, imprime las seis caras). ¿Cuántos elementos del arreglo quedaron en $0$?

In [17]:
cubo = np.zeros((6,3,3)) # 6 caras de 3x3
for i in range(6):
    cubo[i] = i + 1

cubo

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]],

       [[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]]])

## Pregunta 4
El Sudoku es un pasatiempo que consiste en un arreglo $9 \times 9$ de celdas, con dígitos del 1 al 9, de tal manera que no se repiten valores en cada columna, cada renglón y en cada subarreglo de $3\times 3$.

(a) Crea una función llamada correcto que reciba un array $1d$ de tamaño 9 e indique si está completo o no (i.e. incluye los números del 1 al 9.

In [18]:
def correcto(arr):
    bool_arr = np.zeros((9,), dtype=bool)
    b = True
    if (arr.shape == bool_arr.reshape(1,9).shape):
        arr = arr.reshape(9,)
    elif (arr.shape != bool_arr.shape):
        b = False
    i = 0
    while b and i <= 8:
        if 1 <= arr[i] and arr[i] <= 9:
            if not bool_arr[arr[i]-1]:
                bool_arr[arr[i]-1] = True
            else:
                b = False
        else:
            b = False
        i += 1
        
    return b

(b) Crea una función llamada descomponer3x3 que reciba un array de enteros de $9\times 9$ y lo separe en sus 9 subarreglos $3\times3$.

In [19]:
def descomponer3x3(arr):
    des = np.zeros((9,3,3))
    if (arr.shape != np.zeros((9,9)).shape):
        return False
    for i in range(3):
        for j in range(3):
            des[3*i+j] = arr[3*i:3*(i+1),3*j:3*(j+1)]
    return des
# nota del editor: sí vi que era suficiente un reshape... jajajaja ups

(c) Crea la función esSolucion que recibe un array de $9\times 9$ y devuelve si es o no solución del sudoku.

In [ ]:
def esSolucion(arr):
    sup = descomponer3x3(arr)
    b = True
    i = 0
    while b and i < 9:
        if not correcto(arr[i].reshape(9,)):
            b = False
        elif not correcto(arr[:,i].reshape(9,)):
            b = False
        elif not correcto(sup[1].reshape(9,)):
            b = False
        i += 1
    return b

## Pregunta 5
Utiliza el archivo sunspots.txt (localizado en la carpeta data), el cual contiene el número de manchas solares por cada mes desde enero de 1749. La primera columna es el mes, el segundo el número de manchas.

(a) Escribe el código que lea el archivo y haga una gráfica de las manchas en función del tiempo. Formatea el eje $x$ para que se muestren cada 25 años empezando en $1750$.

In [ ]:
DataIn = np.loadtxt('data/sunspots.txt')
mes = DataIn[:,0]
manchas = DataIn[:,1]

mes = 1749 + (mes/12)

plt.scatter(mes, manchas)
plt.xlabel("Año")
plt.ylabel("Manchas solares")
plt.xticks(mes[12::25*12]);

(b) Calcula el promedio móvil. Dibújalo sobre el dibujo original.

In [ ]:
pM = manchas

for i in range (1,len(pM)-1):
    pM[i] = (manchas[i-1] + manchas[i] + manchas[i+1])/3

plt.scatter(mes, manchas, label="Sunspots")
plt.xlabel("Año")
plt.ylabel("Manchas solares")
plt.xticks(mes[12::25*12]);
plt.plot(mes,pM, color="red",linewidth=1.0, label="Promedio Móvil")
plt.legend(loc='best')

## Pregunta 6
Utiliza el archivo starts.txt (localizado en la carpeta data), el cual contiene la temperatura y magnitud de varias estrellas en la Vía Lactea. Usa esta información para dibujar un scatter plot del logaritmo del brillo vs. la temperatura (en K). Este diagrama se conoce como diagrama de Hertzsprung-Russell.

(a) Lee el archivo y dibuja los datos tal como vienen en el archivo. Agrega etiquetas y formatea la gráfica de tal manera que tenga calidad de publicación.

In [ ]:
DataIn = np.loadtxt('data/stars.txt')
x = DataIn[:,0]
y = DataIn[:,1]

plt.scatter(x,y,  color = "lightblue", label="Stars")
plt.xlabel('Temperatura (K)')
plt.ylabel('Brillo')
plt.legend(loc='best')
ax = plt.gca()
ax.set_xscale('log')

(b) Ahora usa el xlim() y ylim() para que quede de manera correcta el diagrama. Hay regiones donde las estrellas parece que se aglomeran, ve el archivo de wikipedia y agrega anotaciones para explicarlas.